apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
type: Opaque
data:
    DATABASE_URL: ENC[AES256_GCM,data:6OZ2MfBmZpbIXsI8Q8AnQgeiEceB2k9sSg/OdHYjgAJIyQLUyF4bVy4DBNnfdxYDMN+n+P61ldBcrpCVLVzGzDjat1aS4oittRpin83uhfJVFSWhPZPQP11qgoRVFwgAwbrABiguhVWwMEfd7BQof1yvTKVcz1c8RYpreEFZy8cXq616sW8iEi0rMJY6C6S90AfqbJe4SLOiCIu6AygFYrRYOltMlAYYBhxQt1n74F30AuqAAbTAjg==,iv:X7IcBxa9cOjPK6JiV5uiLcCKDeY9sntiniZ2QlXqLNY=,tag:Trf/FJ/8Te6KKLW7y4/uAw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:266ik5ta1z3n1a6GyumVPn7TZk8W+IpiPLccPbn5eLBUIo2fj7jgNmhckG43kqTmpmf2c6yJEu/TnwBsSRFHBRt7ZwnDcHpYYijQLhpwiLf7UTnCvRBwuMUUzSci1E7cr981lgthKFxrTQN6afo+ym4guRJt1eT1,iv:wPp8cyJPXyzFNozGAFcboYYRpdz3gqYHXK4ca2Tq9Pg=,tag:uzTekb+uoZ+21x0vLVPoMQ==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:Ros4sYSAtAGi6eODmaXo4MZwAkbhrvMETR+EIN5EtVENFV4LnPyCUvQ0ObPDH5AP/L0+scuIYHAwnUj7+sVK+0mC2Ig=,iv:mkU4sAeIFa6TB7mRQPlD+um/I5Y3B8ElEWcmXU0/jRE=,tag:3V1VaY4PhVgKQhSMwhX3zw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:4XWlGGjQqj3Pu9nDyXQXxGzOn1yYGejYsgzkwWkZEAsID9QaALHCSuDensYye1CJqgOGLtPGC3M=,iv:pXZ/9+UR1R7ADC8wNIkI9nq+yJFWaeVhlLG2SJlUh1Y=,tag:2ty0dvYqKAOQc556lHFGlg==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:IritLmUPYZaW89g2dgVyVNJHBrfOSk466W+vho1HjeSwc/m6fLq2KbTDoycIXdeUGpnCphh4lbQSx5NzLurxJOXRwrUIxW0KOxO2mngI8WniJ/yWC5WkK1TGxGj1V2l6Mbe/fQxlj6iI4MMuCidoWRNtH/JkCZyBfdjncrt2zA872wfwsuYmCVOQl+EQu2NpyAnEZIDz2LW9YUi8neaAUrAmevNzpq4066HcIw==,iv:JFm6cSpAYmyb1kabOYQDa0afq7pWSL6z/ZJpulpVqnU=,tag:xkWjaXQU8m24mOtc5FCknA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU0N5azFVMmRvY2txSnRS
            dCtTYUY4M283Skt0eDRQbFByc004NXpjWjNzCk96L3JGQTdTQUQvL1Izakt5ZXZo
            RlVkdklBWUJVeWJ6QmtsTkp2bTM5d28KLS0tIHBUUkoyYW9lQ1FWS0FFYmhWa1BB
            OXgrUUpYNlZ6UjVEVmxSaG5rT013aDAKiaxpnCmi5a0BnhPzlzXLXy6Z9TbXOtQm
            wiMNZ00CImIbWLB1i4bSaGzi2ziksbiJ0kqbUSgMf6Kdh2qBRiaR6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T18:07:46Z"
    mac: ENC[AES256_GCM,data:JtRWwLU4nFFiQEkEw66CJQ9g3Ms7bZ7sAKBhDx9gD1Fju1yYtJfAnDJbDbuK3B999mu+Qd96292P7MxrTehmP0kJfkZen3Ug652+xWBXaepsh3SP8UJ1Gw7G1sjtDDc05TFuHxOTAIg6b/Pdy52JnqpKUwh0za75cwpunfkItck=,iv:eqWFO049Mw31PMSSF+0xY0Sv8D1fratdQbqenUevNH8=,tag:KZCQOPy9d38QrIucDWlMXQ==,type:str]
    version: 3.13.2
