apiVersion: v1
kind: ConfigMap
metadata:
    name: netalertx
    namespace: netalertx
    labels:
        app.kubernetes.io/name: netalertx
        app.kubernetes.io/component: hub
data:
    PUID: ENC[AES256_GCM,data:UjPJJz4=,iv:+R/ls3Z3urj8/Jc7JbKsVdeZYgl7RONBthS7bFMty78=,tag:l7jmYQBs0vd16isXhzZDbA==,type:str]
    PGID: ENC[AES256_GCM,data:q7uBD88=,iv:K5vHVKxp0p0/RryCIBAPfjQ8beYNmcSE5/o5RrbpdIY=,tag:YP+ELG2m7ySDvtTiX6JKSg==,type:str]
    LISTEN_ADDR: ENC[AES256_GCM,data:c+rrMczQvA==,iv:h4IOiHgNacNSlWIWjlaiN2/Kwy5I4HabA6syjajR6go=,tag:MNuOFbF4XHFMJ1ZjUqnJhQ==,type:str]
    PORT: ENC[AES256_GCM,data:QA8SQrM=,iv:FmKLqD9+LkQFEvkXlqYv1MyPttkV4ia8kdkZjaYuepE=,tag:XlPsjNDd78o7PqkiPGTGrQ==,type:str]
    APP_CONF_OVERRIDE: ENC[AES256_GCM,data:EmqJk5Qu7z/9OhjS7ULQTKCLVXrpFBVD3yFA7HIPJwzsiTeU3GvGM8f45W7gDmTCPxn1boYv+vaiEGdgOR1FZjcSJeQsuCctFo45X2E0BBzmeFUPmtN9B5PxospSGvWSmNErl0K4x3SV9o7QN9akiePeBhnxMRTbegvbi/0dOO1iAZj0642Vk8+snodjiI71GFrPJmOXnovCFLRZ6tIL7IvxE3DEKFOYgknL+H5wOcMpRczN42egODv96QkoyIN1iOcYlflFP4QJlsu3Qfx982Soctxo2rjrlp0L7DArLlMdX3YHbsyX7Ta9Rv7PNfH/Qd/oqtnJirIabZfd6Oa+oojO5HWsE19PA8phWES3xeeVtet17nWrJzLycRD5cgiHyYI5Xw==,iv:xPGIE/dK/97cK6JB7D9Ohx1jmETYrOnSDodUWQCn8LM=,tag:RwQzQ8Nrlu9vHrFP8bpWBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL1ErbkNEdWovOU1xZ0wx
            cDdKK1UrSlZpTG9IeVpkcmlybmRxN2RRSmtvCjBxeE41MDRoSjlmc2FDSk1tQ3Fm
            NzMvMG0wZUdmWU9Lb2ViM0dpekNPTmsKLS0tIHg1NEJyT05aMmIrZXZNeGt2RWl2
            bmMxNVc1YnNCd011dDJnOFF0OGtFL1kK36tlstgyNTcRBxLfZKVY7hwG++m466wR
            OOZK59lsWUd+spq3pF6hWFKBGgrvphG5fcmDVEQlvl2KxCdQ6V58BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T14:56:50Z"
    mac: ENC[AES256_GCM,data:S9JI1wkzpB0rq95cGdMMoDaaI1QSf+uqU8McDtH5Gk/4qYSqk0ggrDEyVdKlfmmwUGa+W8+1rLtkmabZm6l8zA7bjKq3ccdLL14N9AMFibdnuYaMkj+uoaiDLLncu8so0a4Cx20JbKtCOUZbls0KaqWpoxcJ9sNUmQWOfK0LD/Q=,iv:phLYI3R2nxHnPjmPpzJ9h+jTl/IEgbRuBQySvUGynJk=,tag:IDV4JL9Oi9D1iDzcAL2gng==,type:str]
    version: 3.13.3
