apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx
  namespace: netalertx
  labels:
    app: netalertx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
