apiVersion: v1
kind: Secret
metadata:
    name: netalertx
    namespace: netalertx
type: Opaque
stringData:
    SYNC_API_TOKEN: ENC[AES256_GCM,data:ek3spGeGrSl9KKhUotmBFO4K1fWVfzP7va6sAcQr4qHpiTwomLH6CA==,iv:rjYQOYLw/ui+U2ny3jVYhnnGB1EV37FXGILhJrbi3cE=,tag:yDsaEvxTW0YlAO4unC9SfQ==,type:str]
    SYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:4gL5Qe839rLLhwDijEZ84w0Am1E/5dc/iIoAoAGBVr8NwAVcuBoGIKk8ZSbfo+KZQXYj8CA/23V7B3O91w+mVQ==,iv:Mk94PhvGJOXZ2JhKI1mV8vthPjqakiBhqppJBcSaIFc=,tag:oXqdfZZkLL6gNwOkVD1TkQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:RiOnqI7RWMYU+mTTKz1arCXKRPE5fh/xxzAFgbzlwsN6EGs6Ci54LY93HYNx2YHq8lklcw02I9voUo3xnuxppcjycBROpeE8jYMei82HUwGRQQrC+YbFQaZEKfR3bfR841/NkLiz0HKAfFklKpiA0TDju75BV9iZbA==,iv:1coZqSXT9h6FnGzbVvf4Tjmvsx/JJxVjn7oDOVqGRlw=,tag:M9rJ3ICKuaLjk0rQ7nQrBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUmxab1hkcWEvTDI2eVo5
            VGpqU01tNVgvcitiNkk2SkhkNy9aTUQwb3o0CmFVeFRJOExOcXgzR01Wb2JvTHJj
            ZlMrRFdoT09sc25udUxsU0lhWFRmaEkKLS0tIFNsSUFmZkt5RmRYdFJBTFBVR3I2
            aHpiaW9HbGtxQW90ZVduK1NlSDZlb00KwJz7bF8BMz0eJjPJ+8w9Nxo2smyByvqM
            eKP5cg1yl4/aVKxaQ1TY1UXrNQC71mFvv5SfuJ/Rr+YBhPq67LmqkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T16:12:57Z"
    mac: ENC[AES256_GCM,data:Ru5SIDdiaBApuzNdC+QzjK4PFA38dQeTgQDP1PEPXco1pOsmKpjkZ4dTyMmQdua3+LUU/Vrfe0Fp7w/6F8rVRxK2/1uqKPsISmTVXnn5ystxl0AgfGoTwmXCFiQiteytUZEADCWSREzLkFBe0teBAUNo70vq8ipgOH5wBWcSPjM=,iv:rbY/ASzZpS+F/kTlrf7AWryHT3RPiRr/4+YYU8halNI=,tag:8It3x/ZaitYCijNmZ9nCBw==,type:str]
    version: 3.13.3
