apiVersion: v1
kind: Secret
metadata:
    name: netalertx
    namespace: netalertx
type: Opaque
stringData:
    SYNC_API_TOKEN: ENC[AES256_GCM,data:rgnHafnre4j/yCzq1FkT74uBe7Gk8dAh7i9oEBDFuvRQ5tc5s2XT/Q==,iv:6mHzxateHFg6GpAACrKKMYGbsuI0h54qhXDT912CD+Q=,tag:T/x+Cfm9nh+EgNQVO70uoA==,type:str]
    SYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:uN1pxX/Ax92bCYwZk3RrXvRe+keIsO2T7jR80KLabFlabUoUuU4oSTi+ST8T1jLwvjIFnVEOZV+Qi30mcxCWzg==,iv:iGjZKMirodsQm/5JpttJfxjvMdpLB+1lMns8YANxhCU=,tag:w5+7zv2I326wQ8+KbewZxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N1V1SDQ4QVJuQkpndTJa
            TUNHWHlYS05LT1RDWUR6SWxadmZsay9qQWp3CkVFbEM5S0E1QVd3WE54VVdDVngv
            Tm1uaFlBNXk0RDYvcDZ4WHJ3MEUzc0kKLS0tIGkvZE9oYnFUUk1Gak1KRmlYTVVk
            WUJ2ckhmS1VqMDBXdGsxUFdGNUR3RmcKtgUHxMnulvNrl4BE0wXr+GNqNP7jufU9
            q++9tLbQhjP3ldE96+iiUQaxa+waf5XG1wAsxgNVOxgGC/z7ygCX+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:05:29Z"
    mac: ENC[AES256_GCM,data:amaqduvNZy716ZXiqGwPlE8deHg0qv8qyxwYEifVMWpfPgAsepbvoLb2TtrhAnmgyGdKvgQxeOmR/lIay3Z39hu4gBNcf8QOw0mDnqAarLK6CYcQzwx7C3cGesr9sxHnVFiSqsAVTgJ8iW4yTHXbeWZnrKs1S54p2vkzUtyBiqE=,iv:5QZbWfUiEx/pIc9CH/7+NXz4FfMnnQSXq5U1wvF5tZc=,tag:pRNabCOnDeAQnR5yQ8Sz6A==,type:str]
    version: 3.13.3
