apiVersion: v1
kind: Secret
metadata:
    name: netalertx
    namespace: netalertx
type: Opaque
stringData:
    SYNC_API_TOKEN: ENC[AES256_GCM,data:AgGZ0EPWOEKRc1rVCEoGlQf9QY8Qh+GOdgdddGawZf+mGxsrg/3R+g==,iv:kXs5w/oUs5QwWJHZVYnrdnnnlY5lC6dFjKGpM1PZRcM=,tag:Ol/1xIP3+XaiUHTT5NFCTA==,type:str]
    SYNC_ENCRYPTION_KEY: ENC[AES256_GCM,data:p4WnalpQtLerMsClkt0LgVG78qE5WsVUbjm6reBUX3kpmDY0Hr+7sS90hFMDOzahvFm3u7szReSyMUCRpQeOnw==,iv:ltPKuBaOV8wL9J4r8MyYHqAKnQ7FMaUEdoWSETSu3go=,tag:+UpThA/fy8BoEfyPG/t1OA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Q5tnYnyemNQ9eOFdW/7NcV52bS0J+PHD9cohYrkbzDigSrim76d1Arm8T2Fsj5eyQIdB3yrnufEu,iv:yUpMz4DwfS0XBDEec18+ZufAWBpBMQOfZyOPVzlx+2c=,tag:xLJ9EiFxUdqcp8M9Ktt5pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S1ZHclpBMHlWQXhoQlZH
            c203a1RjYmJzRDRxbkVoYTBZK3VtUTZXdnlBCjM5TU5BY3pNWnFCU1dyb2trcVdN
            dXJPbDMreHU3UlpzN29WOU13bEcrZ2sKLS0tIGpzQUdJMFF0cGZwQXFqYjZDRlJU
            RFBFVVpRdTFFQzVEemltZGMvQnFMZncKWxQb3TAzyocHclzb5DD2tzo9WP15LPhl
            8RfVc4FbLAA48U3jXm2AqZXpdPUewVrVs7Nf20FsLP8o0j+Vr9hh7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T15:51:13Z"
    mac: ENC[AES256_GCM,data:1eXu1o1UOcKi3XEecodc0Q6bE0w7/WFEznjV0sRF/a9KtSbXB3pyKyz/ha618TqrzRUdxHAf/x9huuVBnWx8Spd9QvvhKdVeGw3KL/rcQTpz2BM0D9zDP2F1dj+OTB5bOoelsl3xba82t9odRUjd/KWrm7SVrI4W5g68sat/6xM=,iv:BIAap2qanAa3KDWv9He67d0JqEWw7A2gXbM0Jx5Sdok=,tag:rst7i9et2VB7cncVkaXHrg==,type:str]
    version: 3.13.3
