apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data://coFN+9r6g0em2MRQT+RBZj0J4JpFM7YpUvs46qRVGw9+MLHz0tFYKzEPfYCIfZTvGuTEF0a6X8dA2/e/s5fQ==,iv:ts80wq1N2OXOOTXSP4x6lPw7WABBK3nXm1Suwa64Cq4=,tag:wHABbeBZ3zUxmpbiBI83EQ==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:1aTrHVGsXn2UuJUAPUNsHCVdUMCgeVqebTPm0/FSeYISorfJJfUHTHD9/9Yfl6doioFiZgaeXlq5MyAOKoZ2/w==,iv:rpohbtlD8Z+tkq9o5i0luBeVFAfoxcEcopNlyeib7l4=,tag:5vEiu6pVhgLJ/yeFZA3PuA==,type:str]
    N8N_SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:3tQgm/uFC0y1pKYsJpzgQPW/vE2lE88ctfJg6XOaWNDdEIjbS8SITw==,iv:hCqQe8V3t2qO0KhUSzysLru1dTAeuJgunOT1xwHY3bA=,tag:9Z3didVBAVNHAQ8D6m1Q/A==,type:str]
    N8N_SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Puq4Urngcv3TSZTMiNvQxBxDET6VeyfIZFcyQkYAqvrPtmSklO9SSu5DtNEJ3RD6ifjXwl/LSrchFVAMQV5GmBSXE0VL94HEbh91B0COh3wbz0oFaj+G+caSgYTyu/Tvs+KczBwQV0nuE1ITZwCCLxjXRSXPm1e5T0B/7Tf4nJU=,iv:Yf2ghHu3xyHDrSHXPZdqI8d/6gBxQWxZQFwIWQjcDaU=,tag:CTwfoaw2q6FG2l82hsJbbQ==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUm5JcGorN1NNMTJqVThw
              aWlvb0NTMUlOTkthbDA3U2xxSWJxNzJiUUI4Ck5RRHVCUXlodU9KS1piSU8vZDRQ
              M010ZGxyK282Tnp3YTJEWGJzdHFqOE0KLS0tIGd0Q2dOZEUrWjgwclFrNGR2UVZk
              c2JxL3p2b3lRc3pDb0hOZVRYRVM3WHcKCnunq7tgci4K5hVcBII43u7NY5fGxpK3
              CRJC1ofQoRDfnYwgzqJxYbcv0q0Bkc0IM4hNCdy2ZRLw4YQU+fwe2w==
              -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:13:40Z"
    mac: ENC[AES256_GCM,data:uuxn7rvE6Dl28d3gnUJE9DwO6ksmcb4nCHrqdyEpxk3muv44hupN0jSOyOA+IuwF66k7EsBF4G+gtC+PuelFM9t4ikAVXBQyEydd1QTS/nINc35R2Ec0zPMkhkRErO1AfUqbxe8Whkd8xspodTQRgv3D0KVwDDqS/CW3tjYTOZ0=,iv:1NH0gp+GrSYNDdm4UNKQ4bir3VeD0dOzNDdHMsuQRWs=,tag:D1xDcOiWv1YvI+4T4iLyEA==,type:str]
    version: 3.13.3
