apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:okzQOYJ6K61W/z0StjYuuh3bxz+h6/mFlJQSETQ1kHh6DuYFmzyFLSjN2Gh6zc1J6E38FDU52b4eAe081/kt5w==,iv:7TRZstSR9/EqYkmXdkMEk/CnpIZw78Zpm3dwk6mt3Pw=,tag:xVx1JHY/EKHYknxsXi/Ylg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ZwEgAHq1Ad2rsz+Z1Ot1zhQB593CgqZcZySLIidQ431LZs9/IUoQyAWCEmcCzbipRgIGi6SdMplMkkz6HUv+FA==,iv:gxNgm0Zl/9AH3CsW90k9vdrsyzcuifzLpTprxZDo6lw=,tag:SgMabDc4W64z+PYbWmbSNQ==,type:str]
    N8N_SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:nsp2jMBxJLTyFX/C7+k7L4rvCaylUSWUhEHlk5afdBw4xR7g/TWAfg==,iv:8hYA4UWgvPDe7IxrytH/phPbQPTfRj3O4Vz9HHJaYkA=,tag:ojkAQ5jLXdIaJ70PH5Au6A==,type:str]
    N8N_SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:mWVfGbdqhKyKavq9VLTRBaf06J+Fz8K+/7LNoIq8jleAp5LBch2I/ncI/GXigu343KQ2iWpQ72eLsTUwQryLsRflQ/34DdWe1lWiJVwgwdo9CKLWDqvjVEDYkBMXPku60GrJZ45AFaCCf8RF0/fGEuW/e/wTEo4w22dZ1TrySjM=,iv:JXgVc+osIfsPhnWNAvi0+n2Ag53Gnq1IrKQE2J3Hhg4=,tag:wpWdqW8zbVlIYGUxSD3fNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOHRQQnR4QlphSEVtWW5v
            T3Rua1pDTDRaTWZUTFUwN2x2YysxaEh3eVJNClNtTnhJVnFQMCtJRktXOXRITzJj
            NExQZmE0dVlNd24xUHpwS1BNZ3J1SGsKLS0tIHJLQ3FzVnQ5MW5QQTRzWGdBdUFq
            THhmNUVJcW5oV1dtRkJEaDdnUUQwd1UK3mhzfuRWaxlUTADkMJseHIMdW5qGq9Eh
            djFfcUwIA3IQMxHmEJrZ1UedHOZu2OP9tS2qMhUTCxfIba/3QoN06w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T15:37:28Z"
    mac: ENC[AES256_GCM,data:qYdohN6cNSKKbUjLIE44kUOXJW+PYw6bSdyoantRsljmpAcxKsMuuJqB+pTOFyYmBg8ye9w7H8jeOmOyYRQexMYPT1YC50e88+HHDpL0J9ZoV0/kDT8QpRb8jHstaiLfyFWa1EatCtAugIuP6UCsSoESyPttcPUMUg3Mg0DUCUA=,iv:4X7ARkG7qXY0IDbmLGmxOz2tf1Q39vyrb8dKJQrMm/o=,tag:+nYKavhYMWQMLQ7BG3s6hg==,type:str]
    version: 3.13.3
