apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budget-pvc
  namespace: budget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
