apiVersion: v1
kind: Secret
metadata:
    name: speed-secret
    namespace: openspeed-test
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:PCWuyde7V/jk+0sc,iv:jP5stZg7Dsh9nHWwgnITSYmUbMn1NygDslTWQbqSnn8=,tag:U8OTTOOWJc3uOxpH+4KyZg==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZnBYM2NPYWo1UVV5WGt4
              TlpvUXRKM1RuTlp1WVRzOHlRa3cxTXk1UTI4CkNmOEJIdk1nRHFqSndISEtTN1pQ
              Vi9nNTd6OE1CMisxV3czNlVMMGpra0UKLS0tIDROMHZkdFRPWFF4K0V0Ni9kRkR6
              TkZzUHovWEM4eXNxQU9yVjJRWFhUWFEK5j+xmMK4kPgAYFSn9FACryga+L6i42Xv
              i2GV1XuBGdqIn1tj5Wcntvwom5fRYnKSzo58JtY/2+YVfYNnc5/YxQ==
              -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T16:27:41Z"
    mac: ENC[AES256_GCM,data:2mptB1z9qPjLrpoeJaCv0YsuOuFhgBbLcIJ4Lx/gXEoVHMX4md4YOdywgzxYCTw7ll+8BEY2os9Kb9kxXWrmm2kovVOHJK1rqUxQ+p24ONZi/ET+ot/XzR4/I+GveyCttRF+lIdyHpACHUBQFV+zu3DgqCmOltUUx+hDA4xN7mw=,iv:Eack/I17u9OXEGukfTqYN207toD4BHRxNQVTUAsFles=,tag:xloc1C5yRPJ3REOJvfTdCQ==,type:str]
    version: 3.13.2
