apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine
  namespace: affine
  labels:
    app: affine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
