apiVersion: v1
kind: Secret
metadata:
    name: affine
    namespace: affine
type: Opaque
data:
    DATABASE_URL: ENC[AES256_GCM,data:NVsWGu6d6+QgW1S7x9gT1QSk2rvAEh+8oHXfeqRsm4f+tfLvTWkDnCz4Hn9t2MKWhW8lpW2vwcUWZls/xt0N2Gz8ByBjCD54AaYBOjggCJzTTJqqDZijyvH4SvUyZ7tSUSxvIBw3DdOWeqpOpzWMloha+SBhGs5h9d9zJXET8ltea7n/BtOy9MPaSql5RcEDY4L/48decchKSwFMTwi3xqm7F2YOHbPfpiCrkk7AOqg=,iv:gkYDKr6lKAyIYDZ1q7nD2yOLft4CytOEn7aAgv74J2g=,tag:x0DlNoebH7bIpjlTgjOf5A==,type:str]
    MAILER_PASSWORD: ENC[AES256_GCM,data:1eXcMWN40pdZf4yUKNcLa2Uy9COsdm2C0fwumdUyJOu7B7uoE3wg0qJlxmTGizuvkV/GAsWNHYxlVPZ8tftqLoSOEOuuwnlsVsjbkU0AvqBiXDWvmWYQeDPnCRGWzD/rBaukCvtdcthhyAcGpurIeM4XOoKfc77y,iv:yyt79ZU96WpWX01OT9dGibt+/9Bjy8vImOyoHqYAnhs=,tag:MiqP9nluM+qtRt83BtOWyg==,type:str]
    REDIS_SERVER_PASSWORD: ENC[AES256_GCM,data:3ty2umweO53Gq+HLQqHf7VzeAQVl/49YwdegP83YeLl0Wu+ajPMWL/hv/7LUXImQyFxIgeSMpOyHXWbu+lSiYzkUOs5R8N9kkP3jnA==,iv:z69+yyAa4XbqYI65nw56Xv6LBrjmGcLPJQtkiwT8eWQ=,tag:X+LP+JoblF2XU3JIIuPUJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVlRaSjNuaVc5Q1dUSGRE
            aU1SOTJESjJ4SW83VU5ObVBLanQxVUpzUkdvCkZQaU1lSVdLNTY1dW8wUmswSXEr
            M2RJSE9XYW9SL3A0RHdYRVVabnJBZFUKLS0tIGJUc2U2SjhwOXM0VStTRTN5cFhy
            ZnZZRGp0MElBM1VYMWN6a3h0K0tQaDAKJPtFbOdc/3i748CJtUfPISMsD1z9/pND
            W+5zIUJmKa9pqiqk4sYyHgsshmoDeTbMrCMjI8hIM2/SLS4bndmZaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:51:50Z"
    mac: ENC[AES256_GCM,data:Nefeylhx7G+B3IBKpFdjUzb0ubHhWSyxsVi52zcRK2FmIeWW6BlK2eoPmLIu4N7pvijh8TB0Gku9VMXPCjyczkvIgEI3t/9CYlUbC1P/ZSK3IiTO0a/iIO62Je5hcTlDyI+NINCmO2/g+OFjE5tF0q8FOelzdBmVzvf+5TcmRcM=,iv:QVp8Ay4xhzEoCpNCytt4FLG/aJu063VzzC4TjPvnUew=,tag:UV1xByz7uYgU15zVr+oI5w==,type:str]
    version: 3.13.2
