apiVersion: v1
kind: ConfigMap
metadata:
    name: navidrome-config
data:
    ND_MUSICFOLDER: ENC[AES256_GCM,data:NODfuCd2,iv:yG3+STDjPjQQsl9CoCdeXFuEqD/sP4eF6b8dKBUTTQ4=,tag:HmSYqG+yw8b7K58Hdp+MlA==,type:str]
    ND_DATAFOLDER: ENC[AES256_GCM,data:z5HGsFw=,iv:sZf4Cf6Z50gUU876oAAXs9OVA60v3XpZuTRgjfvxzU0=,tag:bM2whk3dxn7BI05wDIDgWw==,type:str]
    ND_ENABLESHARING: ENC[AES256_GCM,data:6q/m6c4=,iv:C+e0zk1xmVfc/40hp/8nH5uPSvXe/3f8gZbEYQ5kQfw=,tag:yrtr+IwRMbVJYH6aXd4RMg==,type:str]
    ND_SCANSCHEDULE: ENC[AES256_GCM,data:6nSEKeliJ4h5,iv:4xL9PvYcCPWIcWjE+UCBtYUtxLY2sq/6/XD+qqXpFZA=,tag:9ReClRDgyOwBScOdrFF/JQ==,type:str]
    ND_LOGLEVEL: ENC[AES256_GCM,data:deD30w==,iv:FwTptbzd6RN6Byi+qyxCczy8uiQUtV1kYoJCJmAoxRU=,tag:q1q6sg91uU7edVdyFBy1aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYlhYQlF2b1pkR2xJMmRB
            aXptNXlkMkR5NVUyT3VrY3RESm1ZSVJJZTJjCjdacHlJWUVCaUd3R0NqbnJVZkJv
            ZVhKU29hemdIcjh3bnRFcG5nalB4TVEKLS0tIDFFa1NtdnNpaWRESVZkenZjcjMw
            VmY0UFNBbWt2aFpWMEp4YW9oMndNQkEKa8Ni/h7tkvdBolzui/x0Ay1GzY+P261V
            FuzOaV2X4NxYNFr0DMRfdqlZFzlUJr/622fvfIZNDM7HJdsuLMw7Aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T11:45:45Z"
    mac: ENC[AES256_GCM,data:5SPHCiw8Ssbsi5Y21oT9jCh+qMJIqMEHC9DCOKU/hqhc7fYj3xIzR5BpS3XQV4sTvhjLCMwiM1WY+jzt9H6UT0u4U4quIm72qE3QU/V4UvdS7YIkKZw0owCScY1FdL+HlmPhXtailWfbJOjqqw3WiS6GlqBhvNYb1jG0rfujHBQ=,iv:ItGKoCnr7r+APCOICc/Gi3f6CH5tw7vYuZYtp/JObyo=,tag:kSSRLCc+UqSxyj0WNTXfKg==,type:str]
    version: 3.13.3
