apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: navidrome-music
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
