apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  volumeName: navidrome-music
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
