# Do not commit a real secret. Encrypt the real secret using this repository's SOPS workflow.
apiVersion: v1
kind: Secret
metadata:
    name: navidrome
type: Opaque
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:PYUpnBBYD43wx3qh7YtWpFWZujRBXzBUGn1ggejAMEM=,iv:OoWVBTAMJhq+7GiJ0ErvBiJtHqcoyN8y8JqBv6Ktdc0=,tag:I92IQFCDCuDX3zRtbtSumQ==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:Uq5twSQXMSbxuUjX4huOPrJiouLPpLQjmbNypIbClPY=,iv:WWRpDcc/wWH4wq9H9QFX1vopW7AjY5cjmWx75JnLfX8=,tag:8N+6VPu7iezhZ/Ko5FhqaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNkgwdHJoZFlyUW55SnJN
            U1pvQm8yMHBTQmMreEVwT3hVVkxuTFZad3lNCkxxQmptY1U2ZFVxRnF2SHhtbU1C
            UlhaVzFYRFpmbVNaQ0J6YUxhK2ZFRzgKLS0tIG9xRllDMGorY1F3REdmWWIzR3dp
            ZmQxRmtWWWFSR1BTM0R2NFE0cjdFK28KdhosJ/wGfmZn+OWqNHqI7wcMIMs7ufTx
            kfLBiGCQbIh1mP9BI/lHYdJghR78itxxDtNqqI2k2IFec8FGaIPknQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:53:57Z"
    mac: ENC[AES256_GCM,data:0vUwXgPNY5+VA2haX0Pt+kmhPUpfR2ixP7IUQtYDcaOU9W+SqxQNT+pAHzdT14TgZWhUxAJTv17b/8suj/im/6Ipn2EqK3Qp7SuOr2sDdwaNGtxjEa73kVgM9qKKdVdnrzdabLYZeWU+WOSLn4u6n742KU9RyaHs076VIZ09nXU=,iv:T/d2MnWso8ZrSxoINBuWVKcOQEbkKVyGtpK+HXnfyf0=,tag:8oH6ldUUSJ06MSbKaeIcTw==,type:str]
    version: 3.13.3
