# Do not commit a real secret. Encrypt the real secret using this repository's SOPS workflow.
apiVersion: v1
kind: Secret
metadata:
    name: smbsecret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GBLOP/s=,iv:CsL+YYaSabBU3rKh/tkD/1cSXs0AcjFrMJE7P39ZURc=,tag:EHV0z7SNBTxEgtyKdj5Ryw==,type:str]
    password: ENC[AES256_GCM,data:lykjIBLnwXax,iv:6vxOBbbiE7MYNBHC11IRo088XS938DMj2Zmo2+UG2AA=,tag:xMMn7C0cY1dNb6i+KpSohw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMmMxMmNvRHRqUGkwVktq
            dmhrWCtJMWlxcUxtWE1rSjJGNU9aNHIxZkdvCjhDOHBvUVhlOXNOOHM0OXZ4RXVT
            YWp1Rm5nRmFiMnVSdlUydlNGUU5qbmMKLS0tIEpGZjc2SVFEbWI1NENOMVdRMzlo
            MzRUNVNibUJkbFd2RlRzei9ESU9hb0EK80oYW5WPFecQOwrfwRt9HYvnINZXmg4D
            ljwo5S+fI9jbMTvAU70yE2wjW/MSxuw0kKx4CL4IIRNnaTWJRoT8Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T11:52:16Z"
    mac: ENC[AES256_GCM,data:8siUKuLhj6/P2Udrn6pXZY6Qaxdshl76bXzNZZyZEuEXirgQJJuBxje6GZZOeyhm9MhRJI2hpaPFRCDUCf7e1Ok/7CntVR0N/eYhBNx+WK352bGA7QJVRlPBWjRT6+fhy1muGkB+HxZVXpL1FIPiBeP5cPeR0MRI4uZIwPC2UVc=,iv:GLdwvy1G/BTa1iheuB3Yg0UbH7xV8+42G7shjvhAVhw=,tag:rVbiPh714YFIzVPTNETmGA==,type:str]
    version: 3.13.3
