# Do not commit a real secret. Encrypt the real secret using this repository's SOPS workflow.
apiVersion: v1
kind: Secret
metadata:
    name: smbSecret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WhRQjCM=,iv:k4peHU2jDI0lYCQPpHcfWGrVxikoHrFTbxmHt6yCqEg=,tag:Ov0DATJjpoaVBvcJq7B4gA==,type:str]
    password: ENC[AES256_GCM,data:zvvWP/mZh1L5,iv:8858z/mW6PODzUoaUVOK5LUFImH+l4lNX3F/9KTHqEQ=,tag:xcNSw6DFz13IHzHolNPXZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3Z5ZW5OU2o5OGUrSFJU
            dEYvMjMwOUJXN25WcEJoMkRZc2JjZkxKNVg4CmhCREV0WVBMMEpMWW9ETG9HaUxM
            WEsxbFZ2aFpSbW1aN3NzQ2V6N2lBR3MKLS0tIHljQitLUUZ2SysxQXhmQlhRbkxl
            cVBXY0tJaEJISXZzVlJUSkVpWnZoNnMKJvWUdouawksPSZhLTBaH8WD1vPKG9Ul3
            Lg2PwzwHZgrATuoabyFfVOusHQufSmPbEnsOlUMtlIwLIyXUPD2XIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T11:45:59Z"
    mac: ENC[AES256_GCM,data:cA+pLYGoEi3F75ihRirqaWBzofPY4QbSoKFVdDLWsY/IopISwfNV14QdVM60cSP+gaXqj5RK4l7+1BXtjwGgvNC3vus+k9DO6Yvjvd9ilQH4bLe7SRfbkay5aphurizY2+XjwxAoQgUINnXAn9N/beGL/A6XsM///h62pdNJcnM=,iv:CfBAdua3AgBr6dn0o9Yc/gRLo4A9zxT4P7rEBmGwlfE=,tag:yikL4ACQi3Nc3V3M3w1pew==,type:str]
    version: 3.13.3
