apiVersion: v1
kind: ConfigMap
metadata:
    name: patchmon-config
    namespace: patchmon
data:
    DB_HOST: ENC[AES256_GCM,data:ZM8xt8PIHBSgE5s/jqHDLHVMa+F/ghY8sKm2+aFDmu65Tf5d9g==,iv:IbzrykW/MRBg1ak7qDjDaXCusVecSXxO3pUaYV5ahFo=,tag:ZKQyXgh3siR0z/Viv/4DTw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:vqHpJJPddqu0jMV/N2I+/cTS3f2w5Y22cEZzQgQWxUnjI1Q6xdu+eTM=,iv:WUKM3WestZqyXFZ/k+hpDDVsU6VJoA/MeTiKQV7n5+8=,tag:DdA0wfpDwBkobYIW6tew2A==,type:str]
    REDIS_USER: ENC[AES256_GCM,data:pQ+eBxjEoQ==,iv:gTv5/oCbXEK/hhz06mzhcpdebH0iiwaf4aJgFb8TEK0=,tag:iCCh3mo41cLwv56sIMm8gg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:+vtVgg==,iv:AsVoFkC1RyZcxVM0vlX4xLaJvQXj/+DzVdqKhi5ZUv4=,tag:IeCfGpv8wed0dy4syjzw5g==,type:str]
    ASSETS_DIR: ENC[AES256_GCM,data:6y8vdo+nLjrx5lY=,iv:X+ILVJlIOck6CRxPneoC85VY03kDfKClN5BMRESeD/A=,tag:/ld4rvHmw8eukdorxo/wrw==,type:str]
    TZ: ENC[AES256_GCM,data:EB+AcM/QYliUMRPK+w==,iv:B1wht9TWn76DPtGolxYB0tcSXByCn0/1W2sbWw1CzW8=,tag:Kmjyi2UQPULnl0DQ3RLxvw==,type:str]
    SERVER_PROTOCOL: ENC[AES256_GCM,data:+080Bvs=,iv:7sWXlFsBGqSRy92/Wzgqjoa4/H9gUDkCqdueAhfUDGE=,tag:/MenBzt8vSGOmINwWESXSg==,type:str]
    SERVER_HOST: ENC[AES256_GCM,data:Xxo7FX514xkLYSa+PvT05hON,iv:i9QbKCn6FmQ7OPp6YhiV+OR7IMMDw7zuewXJ5aBI9iA=,tag:15TGYExF+ABC3OUMhhHV7g==,type:str]
    SERVER_PORT: ENC[AES256_GCM,data:Q9FI,iv:4XxyDkEtmwrC9jFZzyW0mAw70GOh39c4OY+25B+xGiI=,tag:UDWWvzPw3hu0lFeVs2ll0w==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:D2yS06xveut6KZ98M8dXGnrDcG0LdOGe/U4=,iv:5qOSWEOuIeftYsyf725T6MA++IE3kYngv62XeZ6ZyIk=,tag:ZSWhtOOmTkQf5NsLUtbyqQ==,type:str]
    ENABLE_HSTS: ENC[AES256_GCM,data:cxiEBA==,iv:7BzePy7NQ50mHUEqYtt/Oc/KACMYInN2VFiTf9Eyj3I=,tag:lzVzl7SokP00ifGhW4d9tw==,type:str]
    TRUST_PROXY: ENC[AES256_GCM,data:ab1riw==,iv:rXo1cz2eoTnFrWxBtYnyKJeAA+hh7oUabGnq3GYy4HQ=,tag:Hdj3+OoiAov5a5bf0kDnpg==,type:str]
    OIDC_ENABLED: ENC[AES256_GCM,data:yiWctw==,iv:JTGb3XHOsRqqGFj4we0EeHWGC/4F6gRpBsdyuWAsBjU=,tag:ICcGIqsFIZU1FNiFT45hag==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:iRh5NdmVYUExSmAt8+LuCzNa2yAiYz0SzeU14HbV4n7+8YE8nbEhq4bMW1xiuQEMgy7gUEv/+7e/,iv:M1VYhUhHDSdkOLt3znus/7rhmB43BojYgWI4gOOczzg=,tag:hO/SQAvjZBG88ujZelNtFw==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:PsuQ812Ya6u5H4PCoUbVXHHEvvko89NrP09swyvGFomH3g2C42yz8rgR6tGOvIsDrpdUkQ==,iv:KyUvQcwKXyA6PJ857eZaawcav+fs3zjO1vg/F69LXfU=,tag:GCQcQaslClURHXrfXn3UBw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:ghXzahRVbryZbyFwCqkGIBwNto5/uDOO1L4S,iv:fuT//Cs+j1Vq8zLYQ9MvDCX9PZ2nTh2DBXU17GqeS50=,tag:ba7lDNQmym2SGtv0QkJLag==,type:str]
    OIDC_AUTO_CREATE_USERS: ENC[AES256_GCM,data:qUWmJA==,iv:mKdMM+7799eM1L+xBlQdYH6mWRnJUzGB/GelNFQH5BQ=,tag:C/p4mkaf9Q3w6UCPo/QRfg==,type:str]
    OIDC_DEFAULT_ROLE: ENC[AES256_GCM,data:Y2rxcUE=,iv:fp8AZZDur0nXaL4uZajFFNqluf35/g6a5RpY873ylNs=,tag:Www1m3XuIk+ZDtd8kLF/qQ==,type:str]
    OIDC_BUTTON_TEXT: ENC[AES256_GCM,data:uC3tLVx4r3BlboIuKVBaMASnWXM=,iv:aF6jtpT37LHvHxBgZvggUFJvqtaDKsS28D7T3wMzVLU=,tag:h6QTcEyv5MiUd/9CgPkMiA==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:LkLspHY///SoJEyH7AZG,iv:seIEkIRXPo/tx/7uGzStCA1k66a7At1gGnWce6eHucg=,tag:ZtqOBYX7YNRu3PBKk/O74A==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:BrFIXGeTEF7R07SzfSw=,iv:SV1rkq1FTFqnLOVwmcQa9OG1ZZDf7Pivr6BDA/ebT2U=,tag:P3wXn4W7wLdnuk8NlpaG4w==,type:str]
    OIDC_SYNC_ROLES: ENC[AES256_GCM,data:Et1OpA==,iv:DMsqmhk7cjOdAnIzeUReTsmtsPUj3Xbo3UBo28Qh9EE=,tag:Dbaiv1cC2KcG0hx6dX5uJA==,type:str]
    BACKEND_PORT: ENC[AES256_GCM,data:NuXhfg==,iv:S4DQjB1BJiBJsdEU92q6bu5Lnn14pPKgBRNREAXs1CQ=,tag:S5MugjrQXnR23ZqmdvEupw==,type:int]
    BACKEND_SERVICE_HOST: ENC[AES256_GCM,data:3837uVKpX6HCMolyLERLjoyhqGI1jvKyim5qmMYlpCeRow==,iv:PmpAheM9HNJwdFy3mJyHuOK9xzJ3UWaPPb+51QDfoMo=,tag:xiIXtX5QG7vYHZR71byrWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMXc2U3NzZWFkeml0OFVD
            MkNlR28vZ0FCNlRkRC9yaEdVcFRJanZtRzNFCk4wWWpxdGdabkJ4K25EWkx1UlBI
            Z25xdmJUTlR6dVBSa01uTlE1MkVBTEEKLS0tIFU5dnVMSXVEOVRGUElZWWhzZjZP
            ajJuclJqVm02TWl1a3BrdE1nSlk1OEkKongGhpIy70rczVh6Jj8k7HcD/yBJAIrg
            7nSp58S0W/K8cK7JiR0tI6N32IyccwIkPRZECqy38mflUulXfQ0c6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T21:17:02Z"
    mac: ENC[AES256_GCM,data:FuEjPeEMJW9a0n7V4rIi3YxFPecaTxnfrZAGPx7UuJ/gmXqJbSaQhGW+Ny72N/4siKL/qfZYUjiFnbq7tXnjZa5HJipSdzlfh9iycDUkLmhicwRgn1LSVy2y3rNYr506ZHUtfA2GlZ2WH8vvkERhBVCJ30pVhPAXlYXOF/Op4OU=,iv:ZdVxqCFhlJ+vYjnvtvzeouMDk6zZupghMrOMGLMiBYI=,tag:BFClWDCvSLx7Wb5c+kA8xQ==,type:str]
    version: 3.13.3
