apiVersion: v1
kind: ConfigMap
metadata:
    name: patchmon-config
    namespace: patchmon
data:
    DB_HOST: ENC[AES256_GCM,data:A7CKNAU662bc48XC2pp/QEAHjKAIxE+eOVlVd/UF+R49dQVq6w==,iv:64AU1Vv40ealoJNqIksgv/UnkDd8sxQ3C8erCKQz02I=,tag:HSvbYVUj4dOYMylMjYMhdg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:tP18ZZvGfrG/ssNzSXQammKR93eR/yYIbeYu77dQ3S2MqULNM5d+0Ag=,iv:zYTF39f4LMiYRvucZDl4ySlKk/zZOFN8LyfCkcqrSy8=,tag:kUsLErF1XCkbjcNuQdSlUA==,type:str]
    REDIS_USER: ENC[AES256_GCM,data:5RFbw7ZdjQ==,iv:qdnWV8tUBJzoeQX/AUNg6y7z4gikFBSYGhLvKj3Gr1k=,tag:DSv3s7zD9S8Hv4lX9GZjNg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:tIEtoQ==,iv:BDkRbw+GNtRoaHUogcO+ZpbnTV6UeHezcOA5Y7x738o=,tag:sO+2pXhlkO/a22OSVsfU1w==,type:str]
    ASSETS_DIR: ENC[AES256_GCM,data:Qf8C+DOfpaPxt7U=,iv:IST4LigDKtmSJ7iGbMacEgkdb8BSoDyS7NjtAAp+6Bo=,tag:WAbBJjjSkFTffyV71ZM0ZA==,type:str]
    TZ: ENC[AES256_GCM,data:glW0G0WA8gM9qFf1Dg==,iv:tc35EcNtFAKspey30/Xt80t6fu0eIKHaRsLZ690KqkI=,tag:9zirx0+EX3QfuXtto3wFHw==,type:str]
    SERVER_PROTOCOL: ENC[AES256_GCM,data:Kg5Ujcc=,iv:YCBtZtLeMgl3aAmcanUi+rs3cSQumgEiSzP1p9Vmn+c=,tag:7NOkn7Ayb99cLI46kjFf5Q==,type:str]
    SERVER_HOST: ENC[AES256_GCM,data:lfiB6TL5hLkjLfFNZ1iuCh12,iv:rpFZkKJy4GmOPWPDRXusAdayIiKvGNGXbqpXzHebg1s=,tag:ckz27kVrFxf1mv6OlazkCA==,type:str]
    SERVER_PORT: ENC[AES256_GCM,data:EnLI,iv:Ggtg1jtQpblvgue4Ypeu8sZv90N3pUIbMkE5MIJ2SGA=,tag:dT8Io/qGWUt4gXIJfs+hwA==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:4ILUViJfjtrZcM5dHWJQ/l2zWpKL/nrlOyE=,iv:VRCWQISm0HmVM/P5f50kAajUJW74ISGSH04QHvSEArc=,tag:h9dn+nmpImG6F+YrrPsFqQ==,type:str]
    ENABLE_HSTS: ENC[AES256_GCM,data:bRC8Cw==,iv:Gv8+Bu087yqmeEcOiPG32tGmDumniFD7RtDXUb7NW9g=,tag:q0pU3z4h3PJep+PWUaPnTw==,type:str]
    TRUST_PROXY: ENC[AES256_GCM,data:QE2yww==,iv:rXj/2MymmTeddQBjm4Vj7dl9ZITqMjs84csukZnBHHM=,tag:uvbl9DdtRZn6H9Y54ffnkg==,type:str]
    OIDC_ENABLED: ENC[AES256_GCM,data:7wJpYA==,iv:BDLh4SnGaUJEsKrgki+59zCUhrH59qQvvRDtRHNVSUQ=,tag:9VsbxySEHq4nAlMV14PVTg==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:kxmgY2r/wTYSPuOaxR9CCLP8S+lwAm1/mMPA3pq47JPtSdUAVlGPpb+1ZJltHUZrMBjPqgl4AZsL,iv:6fr7SaGmE32+JhGKLeQv+Tvn312IOaIRFWokz3SvaKU=,tag:hpQ9O1lZttUrhroXVqHMzA==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:r/5yrIYQ1qRNJljglJLRR/CfAUEU0MctTt9hM6bS2RSyu/MTaznhJ7b6E2/yU04+/H0F9A==,iv:QIerCY6FkXN8bLjFKpAsOPYmVyCsjkl1eQTxS+cx8kE=,tag:TQDBmFKJGoCnVgHXuNUBMQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:FgbeXv0KtUBGQ8wtyjXTc+T0sAjLxYJBrLDA,iv:neYY7YKJZL3M5OjvVOeDZ2ArwjEIOAy8GruKQO+gHUk=,tag:jQI1ZXRAQwJx4pBwtB/yqA==,type:str]
    OIDC_AUTO_CREATE_USERS: ENC[AES256_GCM,data:T1/UvA==,iv:LsE+38LCijx5Qttggd5Q2LoCZjFOtBpnJij03v06Wys=,tag:k2BtnhIdtrWKUQr8nQi+AQ==,type:str]
    OIDC_DEFAULT_ROLE: ENC[AES256_GCM,data:QSBDmx0=,iv:P6M2GozBAe+4PW3XPoCgW+z28sq9JIL+DLoYAYq9GEw=,tag:5TCqJPSqJy3WvBP3D4WrYw==,type:str]
    OIDC_BUTTON_TEXT: ENC[AES256_GCM,data:/fzVabnHaaJ6FIHwG8eNnHpu3Mw=,iv:ekedyH6eMZF9pzcaoPkEx96vu+K4Sb1EIf3FJv8FYNk=,tag:ZAYz5dFg8netSf/fMnbznQ==,type:str]
    OIDC_ADMIN_GROUP: ENC[AES256_GCM,data:5JOTAsBwksSYNxlQtkm0,iv:VTKcDT9p5W+35agcGfZ5l451nl80LnE2uFxy0MMubTU=,tag:bSs+LLIw4pfYde14K1FZCQ==,type:str]
    OIDC_USER_GROUP: ENC[AES256_GCM,data:OJMSnMpeHjCaRQNpPwg=,iv:U9A12cDdlM5qOcpWRLYqNHfOO1mXAcDYSxw/4pmVyTI=,tag:qI+g9RdW9rTi3QkgzPUypQ==,type:str]
    OIDC_SYNC_ROLES: ENC[AES256_GCM,data:EhHjEg==,iv:7ZDfCpLZg6FvVUB/xuLKRWUjIBGcWvac4zda9zYOMGg=,tag:4WhcpS9Q9kgww1sOCuv7Tw==,type:str]
    BACKEND_PORT: ENC[AES256_GCM,data:fqstBg==,iv:/Bjp0nJt/0pbob4eXA1NtzZCSbD3FXXDrldEzFtdDTQ=,tag:TBeeW4OyV5CT0AWIvZcItw==,type:str]
    BACKEND_SERVICE_HOST: ENC[AES256_GCM,data:48UL+gN2vvzj/GJmaxZWpqf/BoSUz1QImhM3MQi6KC9LLw==,iv:Yhru5i8jlKHfyTxTnla+MiBDm4jM4q2Q94yKDTt6HVg=,tag:MFp1jf1wY+G7tqYnZSRmJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOXFuZlE3NDR0cW1mUkZL
            b3U3R3BMbkx5TWUrclhqK3hnb3VjVS9JejNrCjhZdmtMTFBabEpOMzlCUEpBMWpH
            dnlPT05wS0hlRTFJUHdtZU9adWFOdFEKLS0tIHNUSVY2U1RQVjlmSEVhRDRFM1V6
            d3NhMEtGMUlUcmxkdFR5SjY1cm5qMEUK9B8kTmF31sVjY+v/12AYOoZMl1aANodX
            Y6KMupSA7jJhIwG27CjGxoiTNDt7av5Vq5oMrn02nZ86kd16z16JLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T21:20:35Z"
    mac: ENC[AES256_GCM,data:4gW7zPrqrgw9gkwXGQe/zYrbdzB1p+k3lH+JIVn1nkIC0Vp/+VxezI+X8peRcMSyB1OZ8lTKvbc6WDfQIf2Nn3ewSKeaXxzPDAEdWiDhCs+cGvu+NH1kbST1plkZg5rg2TxtdO9hcVCb6IuJPkeWQPpUVYqfOJFsNXXrMSvGIA0=,iv:vFuunRnMhplmaSbNZ0tsrSq8cfDKDsgttR9myPq4lmk=,tag:lPLdN7A5xmIMCBHy3z220Q==,type:str]
    version: 3.13.3
