apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: patchmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /data/agents /data/assets
              chmod -R 775 /data
          volumeMounts:
            - name: patchmon-files
              mountPath: /data
      containers:
        - name: backend
          image: ghcr.io/patchmon/patchmon-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: patchmon-config
            - secretRef:
                name: patchmon-secret

          volumeMounts:
            - name: patchmon-files
              mountPath: /app/agents
              subPath: agents
            - name: patchmon-files
              mountPath: /app/assets
              subPath: assets

      volumes:
        - name: patchmon-files
          persistentVolumeClaim:
            claimName: patchmon-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: patchmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/patchmon/patchmon-frontend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: patchmon-config-frontend
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: patchmon-files
              mountPath: /usr/share/nginx/html/assets

      volumes:
        - name: patchmon-files
          persistentVolumeClaim:
            claimName: patchmon-frontend
---
