apiVersion: v1
kind: Secret
metadata:
    name: patchmon-secret
    namespace: patchmon
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:zGkLit+FcXlO8vwYZzKJvDGemcEwlbXkilH6th/oxD8woDWBsPWYwt0nWhpRSrHObzdoPcT7ZXYXk4xIbHCIezywyGhCrSukOhNprLFe3ZvOD0c5IaEzjaJ7jSjU8qNnMMoR4nrwwBrYeAxHpuEhHIFOS2qXhEzsoIC0K7F4o0C9EWcM4w==,iv:xw60xpDTJ32ri+rdhqLY52JRsfZItx4BpBw/zOD+v20=,tag:tKl7ozYKp9y90ttfgw+03g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:nCpIo5DAlX7wjIHD87QN92g9p70B4jR7Fzg4t1uUCPSZlFnEiHvzf5ome6GuLdne/5pHb82EGEx/vdY3qKZXjg==,iv:mhxx7nIGxwr/44TyrzH7WR4O+wGLgyg5/dVKbjQy9Aw=,tag:TOvep0icVLuO53+Cb+DUMg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:CTn5O1sMtM+/lUuFmAFZnu6BMKjXO1Cn14roLrp2rrxT3Q6If8w5MBR+8qWIAdHT/MYpPG9JtA==,iv:ZukY2iRm0Qmk1HMR/vjh1mAw/+VgPqb821+6M+lh/7I=,tag:4H/LFFHP9UYUfcpY2tIY/g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:4OGiyqzoCcYXdSEXti/lpRfB+O1Ntnj0r4qyb692l0TS0gYDoS4XRw==,iv:Ce6M3TB7KAp3gFAYx2I3bJv2ZtSvC0YLnRgMzolWFCA=,tag:HiKShnTGHL2np5oEuRq2lg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0UNRTmlpKAOWBLixie/lGi3BwE39NWte9VK1fdoM10v5ju7aIBW6+IGl1MnZb8PFC6pb5XGXKCFp9a2eJrF/zyyZiVy5hibZcUz9CJ5rWGKIyOIz7sHUzpUVsGEGb0JxMnew7MRMYBnf5NJpzLyaiwsJU+/IpAFeYqrgbh13Gdg=,iv:eN/GQjpKoOywVDcyL+ZB2z/M3ix27sqqVR1YDwT1i+w=,tag:D3eMUKfOoD6rbbbG1uQUIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZEdJU0dsTTZmUmZWUU5T
            Rm54bjRQTHRqRWsxMVZPWklUOWdIUDdJQXpvCnYrZnptci84WHhzYzdMNjBYNHcz
            SEhtSmo3TTlDU1lsOHJHbDBBRjM2d0EKLS0tIDRVbC9ucWplMVNXZ3Uvb2NJVTdu
            dnNCNStsSnhvSXRnZ01rSExISENFSjgKRF4RrX1X45+n9Rg0HhfvHixC6oEMOcU3
            DU3XStplBu61Gxqn+fKpaFF75NQ4lrRv4P/odw6HhKUictY6gBkGIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T20:31:44Z"
    mac: ENC[AES256_GCM,data:y9N3QUV8H6Uxv+/U7KEJBM+ORhS6+E+L8wZkj1ngoYMd+NBmW9ni5PIpYtK2STRNvobxD84vxm5udI73XmC5jF3s5uqPsk/wlbNsoGJUQy1chuLVDAUUx4RYA5ob6s/Z2qyb5cVrxvQZMf7Jfs4kV/gHmPAqjqsFyEGmpL3OBzw=,iv:aiClMAlDu9Bv8mq5XAK5ceN/LSUyFL82EWyv4HUGvD0=,tag:7dCKJzlV1yDHOqzL05fGRA==,type:str]
    version: 3.13.3
