apiVersion: v1
kind: ConfigMap
metadata:
    name: kutt-config
data:
    PORT: ENC[AES256_GCM,data:VpZ4uA==,iv:2zMcCn+4QY6E9tKV+a5rdmTUbBQdTw9xGUa0j2gV8xs=,tag:XTUroZ8W5UWkOlSHysA3QA==,type:str]
    SITE_NAME: ENC[AES256_GCM,data:p2OpOw==,iv:g8hm6mDA8lBUy5I62o912BikWWyOzGkuzVaQJi4i4CE=,tag:9VRO24IHXHoPqkcEln0u6A==,type:str]
    DEFAULT_DOMAIN: ENC[AES256_GCM,data:yD92RtgrmRmK/ABdRb4=,iv:QrZuIirEGn3VqpnRLehiYxhYJIW6qm9CZZKdIbG8I/M=,tag:GSpgTsQMZvCVOT2rsIrigQ==,type:str]
    TRUST_PROXY: ENC[AES256_GCM,data:Q1mZTw==,iv:jtG0UeROEcHp3OMNdXnLNQOqZxZRXbzB5lYa9ECvSdE=,tag:gmivelJ27B5Kz3JY7gT/KA==,type:str]
    DB_CLIENT: ENC[AES256_GCM,data:2bU=,iv:/TRuJUd9xo6r0BA7yy7KFnzH1qrwtmIM8prtrGbDWks=,tag:O1Epzupmc0ZeuQbJHImbhA==,type:str]
    REDIS_ENABLED: ENC[AES256_GCM,data:3wudHg==,iv:bXXM71VBFn/7hmgDVzVLk/55DNKP4k1BZqINptK+O6g=,tag:f7blmqAbLol7oTRxIdZX6w==,type:str]
    DISALLOW_REGISTRATION: ENC[AES256_GCM,data:RlYwJA==,iv:vPj80doYiDpqSYO8tI7kNkzSEiwjtz1kYPAHzYZRLFc=,tag:1cqOVrEnIH+/ESPqYRaj6A==,type:str]
    DISALLOW_ANONYMOUS_LINKS: ENC[AES256_GCM,data:U8lePA==,iv:VaBBkk/ANM2n20knTGhmNjhsngEK5gPRdINqpOD/ELA=,tag:7/uy07twEKAFMH7vxHfQtQ==,type:str]
    ENABLE_RATE_LIMIT: ENC[AES256_GCM,data:LhEnFg==,iv:rPO6aD3MasFLp8e3Vf+HbaGl71Io0vZpo1SOPP68+fU=,tag:V5VlY7FuQhaHC1WWeLScUQ==,type:str]
    OIDC_ENABLED: ENC[AES256_GCM,data:6Xn0Pw==,iv:LL3G7r3rRaZQd3tAPyOvXrCRtFGU9HGa6EdcEzgpw18=,tag:bY9oGEYYkndCwLi18lzgIg==,type:str]
    OIDC_SCOPE: ENC[AES256_GCM,data:FCwPClgl2W9CjUaoUht+RDh625Y=,iv:aNkYxH0Y3ZgBtILgTSViIEdKaC8sA9cxC9r/sOki0JI=,tag:jFN85mbBWO/hr5AgWAnF2A==,type:str]
    OIDC_EMAIL_CLAIM: ENC[AES256_GCM,data:JLa+bbc=,iv:efqDK2/C6/XyzuveuILGFPeBjauiMWBSCw7W0VkzZRA=,tag:zXUfUrbGn2OmmMcMFJ+CZg==,type:str]
    MAIL_ENABLED: ENC[AES256_GCM,data:UAjUGA==,iv:lfJzSJ83k4+cFlAkgTDvaJsKcBC9CIOESI/hp36WxcU=,tag:N5ACU9aDj/ju5f48thh3DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UGIxdmEyV0k0NjQ3K2dP
            VStyYi9xRGQ5MVhEZDdpVGpMaG9Jc2JmWkNrCmpmVSt1TExHUnJNVEdOcmpYU3dR
            YnhrNkJtT2Q3eWttMFAyWDFVTmF4T3cKLS0tIFc5dkxFenBWNnMxL2Z3M3V5Q2FG
            ZVVaZ2ZCUEJreHREdzc3V3RIdDhzd2MKtQS+X51MNSEw78pPBPJ2zCqBHiIHYL0w
            XUzfVYeLhs5Xxa7OF/t5oPg5NNPpKI/8qyuaIux0/TX7pys5hu+liA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T10:39:32Z"
    mac: ENC[AES256_GCM,data:hW9FW1KjnoFhOXn86gZKSwwc0IJTjwEFjkl6HEzQkfkPCpJFdRX97QKgYtzi1w491lxNUpyYzmM5xbG5QIN/zJCHJPZ/i2LaKZm177/mmL9rYbNH1zNlJ3K0JeMZKpkzl37bR/XxP6Gbr+0I9AaQ/mptQ2zkRz3214YBILmEwB8=,iv:PMmg32bL4Wppu1AUU1SVDWZ8cKK8rEMhwn3raVztEYU=,tag:xj1w98QIK9EhEnwn9TAtZw==,type:str]
    version: 3.13.3
