apiVersion: v1
kind: Secret
metadata:
    name: kutt-secrets
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:pqL7KrECHLJjAqh2ORKQ8OeOFUPGL8DAaH9OaMVI9vSPfyxlEu7iRQsMbx3fn1MD0EPLB6DoFlnPJRM1EXwcbg==,iv:zjOW3AlKCO/eBi5Amt/L2GbTFrbLMcmmjS+go6Jd9RU=,tag:BYdBH4UGcuxm8Xli1oXkBg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Qxfyn91esaG8G0h4jXildQKATSCOoIr44xhhJVaTCeaEJ7bvAQ==,iv:qlcnDRf0H4BE7otdHAw9jR2F3CNfrCKQUZ30KrjOsMc=,tag:R8bWColZnfEeq98VRvfWJw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:DuFHEw==,iv:U2tFviCHo0XbLSh3HDGpQc9ahph/7/s54yaZyUDM28I=,tag:KZqHGY23Fxyv2IEE1VvrSg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:wetKhQ==,iv:DtnRgszDlrSapMZJIiklFSFUchFMan3uSsdvH39SVoA=,tag:ayIZVBZoeGObwyZEoi2PHA==,type:str]
    DB_USER: ENC[AES256_GCM,data:9H//,iv:haw846THYRWUjvTR3Uso3urc77ONWQaNJuHz8641ASo=,tag:kHWe5yv3HK4Xr5npcm3e6A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:acNgG0eIIXFCQKHkdA32TSgezOJE8mtVJKNfIAIwYvygu8Nx6zYHaGaVdEZlf7VvoSpM7bhtY49dvfqW3tEDHw==,iv:LwHrcR8+EWWBt4glGp6p83RvjhuZHpLUZp4+XCWYT6E=,tag:+xefWd5hiTHMQBu+UYMgfA==,type:str]
    DB_SSL: ENC[AES256_GCM,data:7ITdZvg=,iv:R4L5XlzsquNZzjeEoKD4w1MaRVitlOHTtT4RhpbdOb8=,tag:tO6MQHIewAwVSV9+HwNRuw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:HA7nR7Sp4tiW+TXR/vcNZet2W92JLCwT2qTA2YTtu0V4aRkFB0M+VPE=,iv:NpFEnuTPQSmLDZ4k9uUOEwRZ5tFJeUK7tu8ih2kSGdg=,tag:NYDUW0vbQSG9U3v6ia4MKQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:dztA8g==,iv:JFRGtNEIQxSDaiS57wcVoZraz3a5x10Z0XNxfj1fKw4=,tag:bdgtj4iFrRVt3wYcizKgDg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:rtrgv6Wm7kZNc1zOD+uOwjs8zhiAp2baleQO6vQJNoagPwwx3yuQtCcCRNugr1haXNI8thsKug==,iv:SerW4lKYr3eIhP7wcKacfzXMG08d2B7g+MI9QRS+qzI=,tag:WXHEzxTNCteVF1Ce5iR3Ew==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:TA==,iv:qK7/o+AA0cEih4eEFUI/XUIbtflkKN0Wcm8fXZTM1Fo=,tag:OKAJM6SWdcngW6rt/CcKrQ==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:x53gaMd0nC4cNHriLGs6lUtJbHluVhiNSFPktRWHoWvJKMNjZboU1OQjHGsvo5SIlfjBlS8=,iv:ywR0I6ZOnlI4IP81nWT+T4mRdI+E6o+tQfSlQd9e6u4=,tag:d/vxMrVOa4YicLSSfBDXzA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:cKLU8EUbW55hGi5/RNzfby1bBkjfdfEOqIqU4wMhyBKXCaOTb90lag==,iv:jqowBogefbpg1CEB2vjaLI7dEZOgAnv37XT/TwJQQPY=,tag:dqk3gNITftGnhiee3ZmqIg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:QJcG77qkLOHhlWOchGJ9gOKHEdtZ00VOdKrqVfujjsp90fZ1lhWizbIWhIcxLcFsA3JRUeq6/96vSC2iNOX4HgmT+lao7He1Es9mjtjzXwj6TaypKj7mp+YWoUdwdwFn+dEMyGl3RIX8METn8mPgf8w2zk0JmITjzYlzVjODyHQ=,iv:GXLfluJpxuW1vmwueBXtUSuCLG9G1MNw9BsNgOOSDgM=,tag:0J2WXYAa461/97u8DTkvEg==,type:str]
    OIDC_PROMPT: ""
    MAIL_HOST: ENC[AES256_GCM,data:8lPVpA64/wPKdfu5og2r9YMvWmw=,iv:rxOesOUU27SU1XdhEOMAECcdIlUPZbXHcuC4wZYHYMs=,tag:b2JZFACPtJbdfeVB1g+fiw==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:UKsw,iv:vKoGXxZqJGfGG6dsymFK1RJ/kVuygeJzn0chE/YlcvY=,tag:dubqyIvssolQ687HoMP1aw==,type:str]
    MAIL_SECURE: ENC[AES256_GCM,data:MUdTvQ==,iv:bbgZMMFF+SDa0oVksCb7eMgrQf+dp55FYaOuLFAkK24=,tag:owRUgRwwaKnHt5ZljW7Low==,type:str]
    MAIL_USER: ENC[AES256_GCM,data:FlAx13vVDQHLxaMyHME87YH5JMKuTRFti4MFIA==,iv:7ZdU4HS71sW3q5Wq5omGK4e1cZqDcO2pAzQRHcxG9EQ=,tag:WH0yPrQMuFBGnXc1clHQuw==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:gPENimbVe1nKNEOt4u0J95oJ203E9PdIlPyzap88vdGvVgZW56BG1bU9Zo0aEyfargViIvYdX1iclprnUewgsyRfSXh1IZtCL/84o7jGoyJKDjZifOkz0Fb/,iv:4W/9E56GmkUExTGY+SoxScfOVockwYWaIrV9fGqrGQA=,tag:IDgiwMvnrymwjwcJj5YrPQ==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:q0XPUJif+FJi0+drP7TozY0CtQZnbwM=,iv:cieh+nS26J6XLYfX4QE7Xpe4VHimJo0sbkcuOh4rb/Q=,tag:Oevf42rwEe6RETdu4hcI3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd1RXcVdUOHNCMzlOMW5H
            dGFPNUd6eDFHNU1UVUtSTWc2YXd2UXhrQjBjCmJieGduV1FyaEx5cVBLOVV6K0l6
            NWI4c3d5WGt0aitxOUVDRVBab1NhaE0KLS0tIGwvMUVXbG82ZnlzdnlUY1ovd1hY
            V3d3TDlzZjVnb3h1WmFmaTRnYmI2aDQK90pKb+t7ljtXq+dUdPl+3ajjEBSBVByg
            9ru0Yec9VKpyuF2gjBnECjijOsyhOjTvhewi33jwodvs+XRRnNjwaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T10:50:05Z"
    mac: ENC[AES256_GCM,data:xqhw9mYqOkuhzxuAwcD21U0wR5vpLnNhBLD6YI2Kw9kB9DcPOo+Tne0iSEo/psdhf2shYWvrX5oA3LNQJLgJZ/cOLLkpknkjkUUA41lEEaPOihh6l1Dve/rtisAZItZ8Qm4V1+C+iFrIowLQqh3BIoYm3ZKPEC/5a1nznFJs/Qg=,iv:3XiXifF+Xu9QParud5Q7R5sPPU/3jK0IWVJiyS4V2ys=,tag:7btBvv7MhJX+LVC2uw0tIg==,type:str]
    version: 3.13.3
