apiVersion: v1
kind: Secret
metadata:
    name: kutt-secrets
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:zUD6DIf+azUU03Nu2+XrcD35Ljw/NR4Fld9uCfi90Q9o+LWs0MmRhXmFXFyhtamLv5J7acGpvyGrhPR4gzvvUg==,iv:JCct/e4aSOOzyP1VfPHUE2Xjcv9utS8wEmzbi7Ky7UA=,tag:rtHQTQjUc41EMT2+zX1ffQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:GwqyZXKkD6jyJSq7nIu16/ZvhbW6i6oBTeDsSJkXvOGg0cdSsg==,iv:w3BYGkeZy9zrluR5V/Pu0WRXU3a7k/S0kPbQJ97hzAI=,tag:IAAlataab3kiU1l/6QUt0w==,type:str]
    DB_PORT: ENC[AES256_GCM,data:XuwR7g==,iv:Jn9O5wJFWmzW7gg2EugEfe+zO3UbIMR+1VSQsJUYjQ0=,tag:6M84NBT7qA1LVc62kK/Cdw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:afmNBg==,iv:TnhwF8jZlHEG2cd3Z2KSNx+cx5zzY/DU3I9Il5a8RGU=,tag:cAShuFF3sNboC14KX/GC0A==,type:str]
    DB_USER: ENC[AES256_GCM,data:DSNs,iv:nORMNvJqiLvMeZxxi1GNxIhpwb9S8YbcgtIXahhanG4=,tag:gD7/qL9gSM8yDgEfF+38xw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:agdZ6APqXcEtTR/nGgMXtpeLprqW9lXRIey5U+70AbybeYJpzG5HFXlFN/VBa64F6Aj3hfDF1s5+sdJhTS1z4w==,iv:iQlVv1IPx8jvDyXpMTF8mjCkWP98txJmljrF2ZRhb6Y=,tag:lcVvCGKMnrvwzf+Naa4igw==,type:str]
    DB_SSL: ENC[AES256_GCM,data:E12vEAM=,iv:iq+Ffr0SWxGxStVLIbNyP4wavAwS4B4NKszAxVQLxXc=,tag:D4yvS9lOAvrgkgZ9SKTPyQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:POlWwX+gA/BFcWkEbvDr2IiS/JyxjjDHxoPomEETqbaXUAK7BuVbXTw=,iv:Vif5oryZeBkt8TUO/3vVTTZ5zJ0BNh1RsCmkc+OY2zk=,tag:JrsceRxXJnhFDMOPXjuCWA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:k8iVXA==,iv:CWuELBsGDojyKvAcgLd/DuHqr4195ZoyOxThYiWhD90=,tag:szTtHiV87CQnAX7SehzIgg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:HHzDnuNEt3yt2RsgKrqtoUucqw882CqB0M2V+EpQ1jCzAwDx0ouM0eW9iAgC+HTwMliBv8rpzg==,iv:C83FdH66fHGK+2xKJe+7sbrP92yqgDn9oz/UGQpbUXQ=,tag:F7MXpqf1z6a5xRkMe82kFw==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:0w==,iv:OuIo8FB+NrXmeZ4kn3oU+O0x7wXf3tlc3v6cnfxli6I=,tag:GPGUX/8sthIg1p4WN/NNjw==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:1JUrjisZ9TcwSiNNje2YUM1g74URTXmH6RXcnHA68Re6yOLxVJPLpvvga8kgwkphKbf9LuE=,iv:fCQOxwdHpXG+V6RXVdd8GRJ8mrci2SOKM5KBzcJYPsA=,tag:J9O32AMC2w8kXhyKpViz8Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:QE9OhE29NITSWgxRuIjUnRrye+07ov1+aTHohoWZr+D7QeEsvY5iYw==,iv:HWKUqQjdJ2VYmg0FziDhprUM5Y8BPunFzAGcw7WX74U=,tag:RdE1GndH2DXuYCb2k44Oag==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:T3+Te/f4idVEJPioae2Vn0yM4Pi79V0P+8wqf9V5eV6i0NcKg2mfpOD3gIXsGPkX2UHf9UJcl9QL6hrhueWPUjH9NZcv+saU7aSbb7KZCeltnb7thu6L/p0mi4LzaUTcj5PyfwNcNp4V67M9LavMrlFlmmfnRl1jkRLueYZ9Ry8=,iv:/sHEaaW7Uu9r9biQr1Zvue7U5VN7+BOYk8ZkxwjEnko=,tag:Cpy2mgXal7JKGQi0yK7OfA==,type:str]
    OIDC_PROMPT: ""
    MAIL_HOST: ENC[AES256_GCM,data:pzFx4wT887SRduDKoWowQFPg++Q=,iv:qrkJFqdOzeFwmfR3i9yn83gnkfPsphONa1DFxZMt2ns=,tag:jgY/UjXpIcY+8d7l4ig48w==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:NGtY,iv:cUcBYjsRQ1guQ9WIFd4cEmx0ymSicKY5ci3OHduw98k=,tag:48GOw/xfVJ6G9TdUO3CvKQ==,type:str]
    MAIL_SECURE: ENC[AES256_GCM,data:PTitIQ==,iv:x/T44IIRIKkxvATi8Oqafi6Jecr5vSEM6nEkjlMe9A4=,tag:huvTfAUHQk1FS9vKwPo3EA==,type:str]
    MAIL_USER: ENC[AES256_GCM,data:d4zZBMLpUKsWGyGvH9XMbuGP4EMM/6kFYBk4Pw==,iv:WZbKStFLabNMYFj5Nm/lESP1tNEyCviIY1JVw2udEZ8=,tag:j1Cgukm/rgRr1rQEQ+XmlQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:EOsS6/M3RJ78wB22Xm+019RjPmNtubLJCQ5H5SwWU3Rkz68nQS/vEzi6YjpKV64XnuslZzzTjdNCYaf1WylatixBjvdbYdy92Ipkzxr2A56EuIxAGU41BZko,iv:RjNhqfctH1J+yQy8fajpQl362aXfrPiTTuKNNczINp8=,tag:z2pxhzNbmQhUTY1OtbclZw==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:B16aRuuG8e+KgTJF27/htqCKzesBXtg=,iv:6AiDLsgO/CSGZROrpAUR99G6ee8zgYOv+0NrQ+KN9kU=,tag:4WO9FQ5rPdbnkAJ+yvz/rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMjc5OWo0VVowdFBZUUNG
            ekU1Q3pnMnRCc2JKbmE3anNvWVg4Rnhsdkg4CjFXSTg2WUZncUd3Vyt1YlQzQjFI
            QS82T3gwbzZKL0JMTU0vVm9qTVA5NEEKLS0tIEdBcm1mRk1jcjFQY3plSzFYaXRq
            c1RsOVpoU0IrWXd0RFRlQ2lReVU0eGsK8tnz6l0auTae3LA6tHipe29Uf1VZhemb
            yJkvOLts2NwuXoEuv3yzOMcDNdoDr0AyRhYFkRSZbHjXi+ZVHi9p9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T11:07:17Z"
    mac: ENC[AES256_GCM,data:AzcuntKuk0eJsWLV+sBKnsyfbJ/HZFhIA17b2hdiNSLfzifTADy0SBKDLeBJ8hYHMAHc8PaZNKvGsiy96RN3VsDNrcNp0xU1AeIwEyZ3YtOrOwpRLwsxX9XtyL9TSo5LP2eLKI4rUIri8DQFTWSp3HajBiC29gZM7GhKpTijky8=,iv:A5IoIWeD+9y6AQurvXVEJy5McaXl/mSw75KG8WcV75c=,tag:uMMAOHEPGmtO/XNQWS01oQ==,type:str]
    version: 3.13.3
