apiVersion: v1
kind: Secret
metadata:
    name: kutt-secrets
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:x5qiKzm8ctzQidKWBjjwLmFe/IF8QZxiyPxr7ZT32wXbC/o+TIpeYovhg7+t8vvjdft/g2XqzQQZQjcXLFgQaA==,iv:jV05Z1r2z8Uv95Uw3f5co+HZyK8Jn+WCOowj8UFmMS0=,tag:nSFi4u897XqeAsDpRIHeFQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:ilkmce8o+gdnIkfvugEDSMhBdzpv+7rYV70m9iy1sQMO2kFBGQ==,iv:JLzvlan1qH9kRJe4jm/86QrZNjPuwwtQoOonXInihhg=,tag:8lkQMBNrtqd+aFvXYelRPg==,type:str]
    DB_PORT: ENC[AES256_GCM,data:bG1ugQ==,iv:NmARBrSeySOMht8IK5H7Ps+o1EOGPfUiSKA7NM4CT1M=,tag:a0qpwW9HoEVMTejMPb1Uzg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:v4NDKg==,iv:Pd0zMlA+REPmSbfJ3sBQ2FyLMcNm5ovag5yZ++JqsCU=,tag:/3VhZMf7155CQBuepIrHZA==,type:str]
    DB_USER: ENC[AES256_GCM,data:7scQ,iv:eF0oFHx2Cj5ymTklK69WrMHcXUixLDnc0NQ64YDhllU=,tag:McsGXCnjUSR/2ZeFrBe3uQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:XdqErRQqkQDt4Z0QzNYSb3TaDNRJDS97ml+YDbfNewb6b3VpEsMop2CgJsrH0dCFMZfi7yYtrbMy8VZgl5ltDA==,iv:gMuvLTLiKZBjRj1aJEdYHEuzdAhfv4Vf5YuQAktd3PY=,tag:AsHMV0wDBlA9T30wEkyS2A==,type:str]
    DB_SSL: ENC[AES256_GCM,data:hKhb8mM=,iv:HH/yURaFCP7ga1fUvtGLIPZevuFc21WH1VHu2PAZDEA=,tag:XT9752W1QOBw5LrY+KdEMg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:152VoVUjfkyW3Bho0ydx/rzq3o1Uzc0spKeZrEe7ZPQdO98HCjir7FM=,iv:Ue8cF7o1AFCbd+uaeqR5c5xmRBNF6/ppvfAtSa1EmRM=,tag:MGUyx+tgAjuAmFD73aGGiw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:L2hJUA==,iv:XDyJ7UyMUZoczUKesqooHrG7TNcR1kfrwnQtTFMIQB8=,tag:jARR7myMxOFvj2AhAgEEWQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:JVZoxOQDipWTwisg/0OjVlOEPjKKdBPG+LnE4jN+cynzHinW6eaDnF2jJvBKswDh6TKvtJKNQg==,iv:GImOp16GusoKKyLtAfYuT7xSk0/x+wQuWEzUq1U4n4E=,tag:2XaL4nyyyHMYPz4uKQga2w==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:7g==,iv:tw4s8fZqPllLwDU3jNo2OXjtetGRA1hhtKjkq/Myy8k=,tag:ZqEWLPe0LKyj5cMH5qZliQ==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:g7BtLsmoUoBCioFqg0laN3QX6eYwo0zaLosZPw==,iv:jZtJcVGFA7Bc4JeV0VtDnnAGB2b+M5odOz88EscqvsI=,tag:N4o0aOtyFHRIHuocM7f79Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:0wqXQdkGtzEx9POqzyuM+YVfI/nQ0M9cPhmm,iv:eabkGDhJfLF0J0Wi0XdYoQ4FtPclbEHT2G0Q3hFna88=,tag:oh8iBgbVx5OdrLBJFZs+DA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:VGgKSH/F4WD12sKltFHlSJMEfPJCrlW8hvvuFgL1zw==,iv:JsCffHe2JcfJ6WUa6yWvkU+GjNV4+oGxz+790G1dRMY=,tag:rVwIfNI9cYHSSF08vWFInw==,type:str]
    OIDC_PROMPT: ""
    MAIL_HOST: ENC[AES256_GCM,data:zSjrvkaKB8CBvyPsD/N9pSg6bVI=,iv:2NaSTdpd8JfQodl2bkaJRNDMh89PCJgiD04EKpF5f/Y=,tag:9rppFTNPZ3Kp167/ardzgQ==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:WHtz,iv:IOGAJjG1XXVRKnUYYRob9g3oFYWtivuWWuwCNSUHuuQ=,tag:Yyius7cOAMhOHyEojpOufw==,type:str]
    MAIL_SECURE: ENC[AES256_GCM,data:k6DFRg==,iv:RVRkes1ROHUm/BPtC7Emksz1WnYKYNogsvJu8Dm9F4w=,tag:jPHxgP5yLS4SObb+ydKqHw==,type:str]
    MAIL_USER: ENC[AES256_GCM,data:NtawH962aERHPRwLJj82eyLnIa0P0X71LsFVQA==,iv:sot7G922kIlX1xpACQEHJWaeHoy1h/dUO5xfxDStMCA=,tag:fZ1NdXOQ+drTUnWUqKcCwA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:cGyqCnk+AVf+T+O3ad8QbVwYikPzMFRqqtP6g94pKVee+R3YqC451nZQRfS5c8X7blqaj98U9wjIrCPOcf6i21WNcHCGohxYP3Az6MUWzG8WlXRo0I8+4byd,iv:pfnchxe6inw6UqHe+fFeeRDhnl5rxbjvEa5SizltsYU=,tag:ZgBEeafyGRfLidFADr7l+g==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:6mFA58Y4fkORKvTpIuHJu6W9IGorkmM=,iv:9yBdEfLOpe0+khWKKhrO8r15TImHhjGVY000V6M3ecA=,tag:At1xTbgJ7mNke/9vTZT19g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRXRGS2ZGeHpyR0oxMExD
            cG14QUwxbTY3aTlqb0ZCaFVKdjF3OXJlbkZFCmphY1NxWDFqb1RnZjhtSGhaVkdM
            NVRXYVVaaEVTaTJjZ0g0bEEzZlgwMGsKLS0tIE5wUGxWVFBnRzJBaURvS1I2elFw
            VG1FVUhNM29YMkNNNHBKU01VVjFNUDAKa3a7C79MEp4S73zEsfxcEJTB6yq04L3g
            C9tIKBFgg6/UTdAImdAhqM83Q/R43PKRv88wbO1X1gVFR6FJ0Vv6Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T10:39:37Z"
    mac: ENC[AES256_GCM,data:wHo4+BRc6UoTYRUn4FWJRE8xyL5bML/GIfyQsZ/hNULtiZN2Atsuly/xWrzHyHyJn+mOtjnpip2ZL6Wn0lDyacroubIFNBYlB3GGq69hTSolZlIsq43WkxOKuL4Kx1z7jxC3Z/aWLaDLJEppz3zAy8E6P2DXP0muUqd4ejPycwo=,iv:9jGrqYizQqFjzJgpku8scsO1EBu9qaefdqRASm42w+0=,tag:LADUfixlwMHD5qxIMOlizw==,type:str]
    version: 3.13.3
