apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
  namespace: zot
spec:
  interval: 10m

  chart:
    spec:
      chart: zot
      version: "0.1.122"
      sourceRef:
        kind: HelmRepository
        name: zot
        namespace: registry

  # HTTPRoute/zot-route is managed separately in this Kustomization.
  values:
    httproute:
      enabled: false

  valuesFrom:
    - kind: Secret
      name: zot-values
      valuesKey: values.yaml
