apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
resources:
  - ../base
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.yaml
  - httproute.yaml

configMapGenerator:
  - name: zot-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
