apiVersion: v1
kind: Secret
metadata:
    name: zot-auth
    namespace: registry
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:JRtQLwNxjp1ewQnKNIeV5noDt7q9N9142DDZVO/CglpVyJ8NmDE0TTUOUVhKjKCw3mB364sNrq2PbmVeE++FDHQN,iv:5jfibqce3aVuzQ/mfKIr0SDcc4e5TsSNLRuVIuBH2FM=,tag:ith4D0Rsv+EJS6TvZJnwrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U1VpVFFhcW0xVnZ2L2lS
            bXcrRGIwdmhKRXU0SlgvZndjTFEzR284bTBNCjE3QnZBM2lCTU9yTSt4YjR3UVRp
            K2J0bmxBM1lLc2MrNzdhbXBHQnZwa2sKLS0tIElEVGpWaGxJbWJGYUs5UE1NYmlw
            QUNtUFRGaWk4bU1ESzlFSWRGRHpiaHcKLY50mGc33MTkHM1/x5eZaRtk1JlUq/1H
            evKYXnvVxExDwOGmNjoFr8nhblGTgmlfzbeKZ67ywuuWVjv2Cinedw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T05:15:14Z"
    mac: ENC[AES256_GCM,data:7P0MqQlzmqUCQmqhocG3ozU41+pgO3U9Zk7zMA9pxna8PWqoPVR96GmhX9Hgmp2YgHg8q8a+S2aDJLPkKIrbC5jblfOj4QUAa9Q8GTX1DSRFyOFwWKDYhjBFqDGuzgSIBvaObNwYTUWla1dAI7Hz1tAwI/aXa7LvDEc0RouvInY=,iv:6kmMvAjKt+q264UXrIHh1zXILo/oaIcMSbWAfq5x0zI=,tag:KoHCIrbB/UZgZTW+AKcEtg==,type:str]
    version: 3.13.3
