replicaCount: 1

image:
  repository: ghcr.io/project-zot/zot
  tag: "v2.1.18"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

persistence: true

pvc:
  create: true
  accessModes:
    - ReadWriteOnce
  storage: 20Gi

mountConfig: true

externalSecrets:
  - secretName: zot-auth
    mountPath: /secret

configFiles:
  config.json: |-
    {
      "storage": {
        "rootDirectory": "/var/lib/registry"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "readTimeout": "600s",
        "writeTimeout": "600s",
        "auth": {
          "failDelay": 2,
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        },
        "accessControl": {
          "repositories": {
            "**": {
              "policies": [
                {
                  "users": ["fanto"],
                  "actions": ["read", "create", "update", "delete"]
                }
              ],
              "defaultPolicy": []
            }
          }
        }
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "search": {
          "enable": true
        },
        "ui": {
          "enable": true
        }
      }
    }
ingress:
  enabled: false

httproute:
  enabled: false
