apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v7.0.12
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  redisSentinelConfig:
    redisReplicationName: redis-data
    redisReplicationPassword:
      secretKeyRef:
        name: redis-secret
        key: password
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - redis-sentinel
          topologyKey: "kubernetes.io/hostname"
