apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-data
  namespace: redis
spec:
  clusterSize: 3
  acl:
    secret:
      secretName: redis-secret
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 999
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-cnpg
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - redis-data
          topologyKey: "kubernetes.io/hostname"
