apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: redis
type: Opaque
data:
    password: ENC[AES256_GCM,data:4RgyyxdiLSkE3yDBRkrLuEEwvXhTCab1BX2lA1uaMfu06L6F9kIRHNZQh3B/BKqGHxhtql+C1l5gDCKdjJAHDtsEsh412/1IopvHWg==,iv:nTxa69zgIWAtENzEkNDE+8knqRvl5dXY7nzNvI+aFsA=,tag:2hQrRuvvyqqCoC38BlLoUQ==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMnA3aHllTHZHMEVRQ2li
              UEM4MUVrUklNN3hmZHU5Kzc4ZFZ6Sk03Y3lJCkpHSVd4cUUzek13cGFXT241alZh
              THJpSS9CL2VxeE9hQzNsb24yWkRQSHMKLS0tIFU5L1dNM1RuaUt2NitFN05odS9J
              TU9UcDUrRWhzQ21taHowVVhrTjhiOW8KoUu/kTd+DQQ4uORgGS7raJ2qHrcGGGet
              9doRV6GuFET97s30te1AmUIqzi4o1rGqUDcIR2G0+IRs7Ux/oiCRZw==
              -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T10:10:33Z"
    mac: ENC[AES256_GCM,data:s77beszaKrChV13Jv9quO1FTsgVBxCIjXzJoDBDjxHyQAYH3WRNjxi0CREdcAfS0cI9C1sWWZpgJvrmzNiJ/8Hb/C9XtPx3yposjqiQ0xRX1T8p5y4pDg9JA7wIx0KYbYXZENh0yUgyXemmvp8AD9kCLqya4HqFkT5xwuK24lg0=,iv:ofxY6FKEcocHqCcRhVJ3ZNki1uX4dztMkKtsqP8zgBQ=,tag:AWeQNLoHl5ExF8EJ3dwVjg==,type:str]
    version: 3.13.3
