apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 5050
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: pgadmin
            - secretRef:
                name: pgadmin
          ports:
            - containerPort: 80
              name: pgadmin
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: pgadmin-config
              mountPath: /pgadmin4/config_local.py
              subPath: config_local.py
              readOnly: true

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgadmin
        - name: pgadmin-config
          configMap:
            name: pgadmin
            items:
              - key: config_local.py
                path: config_local.py
      restartPolicy: Always
