apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:GbVe5GctAmtl/VSiDtcmBe2JBEH+2koaSq7t1YUlfo9NBNOinEp/Xb8qRqXFOZ3jTsM=,iv:MVSysq1ywWP/pAx7jtAG28Em1k5OEtu/h7CULHOIz0k=,tag:AsGMQ1AZLfPUDOROODaPrw==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:OJbjn9x7YQzMia+xHnjP5Un0UF8cSh2RTvqreBmiDwds8qbxF07SxQ==,iv:AJqeEoiSfFPjsQ5T49lqOaaLYeXKiRQjdCfAo+jussQ=,tag:eUmAAo4XQ++qnvNR/OMuow==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:WpUkgJtbU5FOWQFRWNYZuuq7+Ah/XwG5grJKxGBJqrOCxeemdMuWerdcG0OFtA+KbTajEVONo2hP1s/PxAGQ8qvIS0wPHFBguzoVklV6/SuvTqf805OKtUBcFxDFyaw/ZXM8f5BduTqm5mzrD0vLm87GCVUrgtSlkZJK8acSlLI=,iv:iLZDBZ17S/4HBKI8jvhTypbgxSxARj09z/a9QQ65jB0=,tag:3ofTLNIOkxwW7CxA+powMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWY3akdXQXBUK0twb00z
            cE9WVUtReXdSeEE4M0JrbUt6YTJHVTJSVG5BCmFCNFVBanJ2TFozaVByV1FEd0JQ
            RkJjNG1lUUhrMjhUYXkvVHJyY2JIN2MKLS0tIFFOUlppZXB3bDV6eElnelZLSFAy
            Snk1Z0dGRzFFZTFzeDhiUWFYTlVKZkUKnwtbcuIsxOWtVBCGQlvUAu/TD/P44BC7
            1jotJPuFDp0/h1F8FsX02NP1/uU0bUhAIi1TQ6779xyPLsfkjqUjCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:17:36Z"
    mac: ENC[AES256_GCM,data:oNEOUqnlU131XH43qJ66c7CNiS/Sm6WyBCnwhfHa68IYsERi+GUqfoXS5qTf2F4YyTP7AwQp9COl2ezmHVl+nf/xk6UCneOON25Hgfzod07XEHYenKyZhxVuwoyAMdRocT9F6/Zn8cV8oeYXwDNuJ+WRT1xqBBMAvDYZuxOLhGk=,iv:49iDuMH4j4GUddyIgUZbhI6O/yH03p1g6HYIUbLgyWA=,tag:6O/mKCoevVKILHpfZjdVxg==,type:str]
    version: 3.13.3
