apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:QWW1OEtFy2b5j1EtFSSk+JSPhhWzRo7rBWdCvw9XmfZwmvzaCR8wM/1ntXJArP7q3/8=,iv:tW/rBprnzRA79nx2ab/8MvAsvuqmTih5zvHbS7RmNJg=,tag:YSoz+eGQx1p1NwqtBCU3Qw==,type:str]
    OAUTH2_CLIENT_ID: ENC[AES256_GCM,data:Do7cwdW4WQ7GMq7xIzhzez48u85dVFLLGUu9r67mhfY3sODk4e56BQ==,iv:k1Q5Fs6r5A5XwOeQKM8wZcKR11x6NnLnUYkZzGoOzuY=,tag:95tPCJ38JON5ST9OIhaXmg==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:WJJbRhqgRez38F2sxeYsc2utioeTFYUxFKQ6zgkVzl3qDBaOJaIUuKZ/s1HzOHG+zXKU9CrrYzBKg0ZFoeCc80xXHVLwCWLCC3otGzwI0cQXwGwumsB5vB/kAj9Dl9w+S2qCvSQYfJN4koFrC3tF895sMLM7tSC4OKTcbSoWqeQ=,iv:M26Pyw/ddp1s9QrG6Nwly3BdRgKzGebmFhZhKd5YSPg=,tag:8HN3tSJZKCOYxcST4MkkwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdGZubGlYRGtOamhBTWp2
            dng3QVJPN3lrYitqamVzRHJEa3VERHNDc1MwCnRoVTdWZkcxL2tTdDNOd2JmOTRP
            RFlYTEkyeWRlaG5SRGtvRlI4bHlzZXMKLS0tIEF0aHVlNTJ1ampoZWxydjVreGpx
            VENoNTZoSnNCRHg3a1hCd0xTeFZyZEUKfW98NfJIPqa6JFsr7E22xOtJQCAwQtYQ
            qgxOI9/3m1jbQhpak1AQrx7hiv04TjX4TfpX0v0iQSAmTf7V2iCJsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T16:55:25Z"
    mac: ENC[AES256_GCM,data:Pi2vk1pXAqMEvJuLdTvU77NiF2zQCSznFMVLIYQon0bt8wQK7gCXCfnqfP2Xoo8q8VWwPwZkGrm7pNhJCpOjl8YlBoQ3k+ab+x2q0xdH3wz+QW9H4IpxW+1SK+0/Bo0FYO6Ttc0EyTyc/YY9BnO77b9ysyXbhQQf4wjDAKuZSEQ=,iv:iB/FX5HjCJAClN85aUrDfL82JxW+A4NCtRHQw1YiElU=,tag:FED6nX7W496aSQcfo+WJBA==,type:str]
    version: 3.13.3
