resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  # - target:
  #     group: kustomize.toolkit.fluxcd.io
  #     kind: Kustomization
  #     name: flux-system
  #     namespace: flux-system
  #     version: v1
  #   patch: |-
  #     - op: replace
  #       path: /spec/path
  #       value: ./clusters/helloworld
  - target:
      kind: ServiceAccount
      name: source-controller
      namespace: flux-system
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account 
        value: "hello@gcp.io"

# ~1 = /
