apiVersion: v1
kind: ConfigMap
metadata:
    name: netbox-config
    namespace: netbox
data:
    PUID: ENC[AES256_GCM,data:LQ==,iv:Hj+ZSw77o7j+g9WtybyDsTA4Up5QN3xWSAhJFZ6wQ+E=,tag:ZJn3+vnz+r1EUM7jzj43+g==,type:str]
    PGID: ENC[AES256_GCM,data:Rg==,iv:CzeDU1VneDc6tos1BpTp4JiFuK6elQMFHBfW5YGT2Ew=,tag:ceQE5zdq+ZmgG2v9jiML8g==,type:str]
    TZ: ENC[AES256_GCM,data:2pAbKBF+gfYY45PfDw==,iv:oXYU/C5Z7J4zg0P+BFjAqV03YhVUjKTuN8vWqZfLZko=,tag:u4ajOLPldFx162xoTmbf7Q==,type:str]
    SUPERUSER_EMAIL: ENC[AES256_GCM,data:kZ8E2Sw7SR7Lp8sEfGaN0w==,iv:AIpeq2tqYaNIhwzq9Z0NXwSXcmjExpxnXy5km1g0UpA=,tag:fJVh/4IOtHIQv/I+iLxvSw==,type:str]
    ALLOWED_HOST: ENC[AES256_GCM,data:RGHNXIMq3YXbOZGxFKNArQ==,iv:nlM7p5Mwhhoujp+LgjUJYW8hd8bvZNOgkHLsNSW7gGs=,tag:DOOw5orUUBgMg5QB2NS3Xg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:0xwxaukr,iv:f3kJTMwhaYFG10g7AKyD+lc7S6jbge2ksLmbjkFVqU4=,tag:d3WTwSNSMo0+q+crLzh5oQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:b/bu,iv:f68vrrdk9hvFxfBsV+chN1L3pMtS8gqI52tMJ8LSWyw=,tag:cyvV0p5RRaEpPYtHg6k+mA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:uAWKfPSgATjgc822aG6qr2Mlb7ID3lVQpvYYUi4RYvbcVtvnlQ==,iv:xBECMZTDuHqibRKL7wOWRjsv04Yg0gZvdtUsYBlKFqE=,tag:WDANGoKDb7rR1xhuD9N7rw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:P0ARXupg+ZpOZ719ZVsYj7RtpUmhPk/igeap23+sZT2HwO98yWri05s=,iv:ZJ3D3eX9/SSs9C79O6rkbeHgJOd7ZCtbuRzXh38Zd2Q=,tag:M0Ahseczq4zrcC7E8V7/0A==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:QiLsONZ7JQ==,iv:bgo0SBm0Bv9FzmtdCUpbMb6c6DpNNuqqPtbt4dXu5AA=,tag:NHUw5+DR9dl1L9yAZItZiQ==,type:str]
    CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:ukZb09TuxsKa1tLDnaFV7xqECAHGoZ4N1jY=,iv:4n9pas8kbsLjqxGz0g8iwBEpUnXngz6iLvEaZP9frwk=,tag:HR64aFHZVoHmgbLY4tCNwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOUw1aERTemxRdkxMT2oy
            SDNZRUJGWnZWUEJ2TzlQT2tEUUNZbGVrSm1NCnNYSW5KU011dUZ6Nm5ZdmdNMmVz
            UGk0dGtMMUVubjdaWWMzaExlTW9JWGsKLS0tIG9uUGdTRnMwYnZhRU1zenQrc3RZ
            T0pFUlZuTmQ3STVqVS9HMGZCZVg0a2MKk44kBEfMqffSUKp/ACSOSXzirH9TBKjm
            MTvNffkjRLHTUOnuzUquXFfs/QH3b1yl3D+87amT59ecIQR8POvuUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T19:40:04Z"
    mac: ENC[AES256_GCM,data:3RYXFg6pD5AQ7Izxd0GGz6XQOuABYvtp9rNpJdNIO4AaH8vkKdknTIQEohfvu9yLC2uScmWXB8kkR7CR68L4bmq5VGZ5bE2ErvhnBopgnM/1JMFnQIj5nnLN9PdP81fQmzpD7Ul/wA/VI9Xgku5yN8xPKGXWdFZecNIYQ0Le53k=,iv:il3s6bkVXS7hniQzo6eTIgC8fmFjY7uMEg97VZcWCy4=,tag:pRks5kLki3zpOZCicyJ5RQ==,type:str]
    version: 3.13.3
