apiVersion: v1
kind: ConfigMap
metadata:
    name: netbox-config
    namespace: netbox
data:
    PUID: ENC[AES256_GCM,data:Ng==,iv:67fz3ZE72fZX6zbF7o1JsfrjuQ6tAkc2AZ/XVEJp3j0=,tag:neeCjt6mGCmpJJ6U/sOFTQ==,type:str]
    PGID: ENC[AES256_GCM,data:Jw==,iv:rPvWWDuznsNVubbFXjUJe0l7sZnYuQZdim4OQLxUfeo=,tag:JalRJdBV0/IPnO+TS1SHyw==,type:str]
    TZ: ENC[AES256_GCM,data:Fg6N9tCw2u19k4QuJQ==,iv:4CjLfOcgHAcA2+kiU4tbb/QgPMtb6hjGLrNLxlyBZ9g=,tag:CMgosOLr5P/3uJ0IzGS6yQ==,type:str]
    SUPERUSER_EMAIL: ENC[AES256_GCM,data:tHp3P3lt4BB/1ZBW5p+usw==,iv:01b52k5oZM0+0ypsg8vqk1+S21384TibQzAk+VYYa4c=,tag:lxun6iOXWoZFVa/nn/uFLQ==,type:str]
    ALLOWED_HOST: ENC[AES256_GCM,data:LT6sbfi8rVovZ2mRhYWoMg==,iv:vzbfbgqnjvh3pdDilXtn8Y74aFVQR7pBL55N45/E5uI=,tag:xgz3J3cHBiKRJtQlnh0CRA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:gnH5Njvn,iv:oBviokwiIprKVq55tINB+xp9fkWorkNPj5arjIKmlIg=,tag:jBk7oTslz7EZnoD4kqwVjA==,type:str]
    DB_USER: ENC[AES256_GCM,data:97Hx,iv:Y/DR1ZiILltsWUlJUgPbTnKm4TCq3OUr0BTruFXyU8w=,tag:gOrgZwD7RWtoY/2in11exQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:1VLEVLDnpJe/cSjFPJ+jAE/n6LRA282g/9x+VCpOmePAfAkGnw==,iv:PDE/wt2p7fmh231SUAP9Hh8BD1Pu3Z7hOPXQ5vyVP5g=,tag:/qvpYTquTCLqgmMtk4Je3g==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:925xZg/RtIptk0TYxFVt7sIhBGzZA5J5MH6wAOu2YuWLwttESpC5jzI=,iv:2rVolhTgPb0lwAGeVfy4KXd248VNArYIWTjD5uBL+kI=,tag:3p8v6jaQDMvBIVSuKWIQyQ==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:QBZy5d4C4A==,iv:wIdXwsvSUxfruavggwpN1Pg54h7EdbZvvBdOCOoBSn0=,tag:Zq6H84l6XjpyWLsHCku4nQ==,type:str]
    CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:p2pDK7V3eZSucINZOPS8fKdFfc48jTrK,iv:Sv4+1XujCAkrKPRJotqOwoxBOU0KBl+MGTc1KRGCmBU=,tag:TIfdw2HLK/r/LDWyiS7xjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbTZsWjVnVGJISDRLbXc4
            SnBQWnlOb0dWUEFXaThKR2E1emE2bXRTQUNRCk9UZDQ2QmVJb09oanNuRTZCWHhN
            SHpqUjZGajhpVlhZbjF5ek5CdU5IYm8KLS0tIE16YmVmYTc3NXR0blJZWmRkWWNC
            aWZIL3ZPRmNIdEFXWjdxQUNQVjU0UjgKVK8dvcFEHcid4Ur6S01ZeP0zZB02TTKN
            HpTbf3DFxh6AI4zvmzWe2zCiQ5uhbxXv3NvPsdBmAcwE7FsiCviHUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:57:01Z"
    mac: ENC[AES256_GCM,data:VNawFQ8pAWCMCtEFvzgn1Bx6DQFGAF3Weh3DusTTm2zFxwb+GR2xFprSSz3zll8WA+UInPWewxJ5YdtcXijZLTf5sfapwiY7igSqyf4sIzNAlNJiS5z9SjBMTazAOUuATy/AlkND5rtqXKdAfK8sM9bhDwewqG+7wnIJSVdvMtg=,iv:DpHisNkFguiGW1zKPT/i3YNGOSG//ALBb99wffFy0HA=,tag:eoHBynZM2dlb/19+DTGc2g==,type:str]
    version: 3.13.3
