apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
type: Opaque
stringData:
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:jFPQ/fZE6Zs6e0eJWJxuuQEAeoJUVVgzV7S0B5smOjzIsql0sovb6ddmyqZmTO0Wt3o=,iv:SirSel4ah5pv87Gj0dghmt+iIwwRIw1BjEdwrFtpCKk=,tag:6kkMqlvukZx1TTC2MzthBQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:F7Fo8jVYiZs5qhoT5iV3duLQd9vIW30msjgJ3b9k1o/+nJ77ShuKf84RUUgHNphbU+6aA0eaidaIRDBu1gpvJw==,iv:qp4CH2k32LdD2MU+I3y2dT9KjSvF5MrXZ1uD3xbZQ8A=,tag:VIn6WuhFLDxgjjLW3oYiSg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:GQ8EpKaVvUoaBl54ukKMZklmDkMBOAvdosXMpWPF7B7zrApTnkdMJYFb1sT/FVE/Ly6y8IsDmg==,iv:FM4BSrGPvPt6/w5gGqPMX0Izn7bimrjNi7S3PK60Qvc=,tag:3Fm0H+/sRyDLNcQjquhm+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRUt2NmJHUzBjNGJ3UVQ4
            aVhveWtvb1hYN2h4d25DbEUwaTN4bVpzdm5BCkVwM2hkTTJFV2J4c2graGdYRU9n
            VXQ2NEJzQ0RrVzBnTXd0Z0I2QUwwdXcKLS0tIFJta0I5VVZFMHBqbFFuNkVSUzNh
            SGZOK3U2OWFVLzVYaCtlUlRWT2NWY28KzKPMI/EcpnYVT+5jd4hfMhCzFXzPS6j4
            loi3smH9xr0RY3LKE31Z6HckFLOOtH/eW5ZFCNH6iHLAjonG/W5dxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:57:06Z"
    mac: ENC[AES256_GCM,data:cf2HsJTS1vlsZKXAMSpSrw5vJftVQTlrp7UfcyMmw5PFHmqKVNcBOZhP9d41/Z/OGdn9WMmMB6FHLBNGrZR5MaPpgAdRbaoaYCa7DCbTU3i/rx1l5+oeWjE2JB0nAMbUC01AqX9GCG/l90hMa2z6logjWTitvz82o+ZVVt/7PME=,iv:VPPkgxGOucjFSpL2RXKkkfO2qNJQNxsr2alxHeY6f9E=,tag:MPOF7jnWWMOWpugK99V91Q==,type:str]
    version: 3.13.3
