apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
type: Opaque
stringData:
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:OJIlhMN54xRsrt7uw09tsEMiacUnm8ZbTxAdPjZ82JjAgF3tOcPRJepEjVsRQNAr2ok=,iv:+yjG2jnZDkrVHG3j8aYkYD7pmqjKAurul0YSCc9TcNM=,tag:Y6eK9OWaiJJx0aZggjhjIg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:LpiZJhm2sisptO+Y/0K/1c2EXtDgbo+VkwFjh+ifQKOuMQsW0NQJ36yt+TsbGU/GPSBBvhaoEuZLrhBKp1fDIQ==,iv:UM2EWDORvF4LOJPKT/PcFQKU7JCdcEM+S+fYzTjUv+Y=,tag:Uvx1fj2ofnRcahgHFcKaFw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:TDdjxUL+ujI6z1u13/gyVp8v1MlO2oYiH6iuu9q4DGV6FHN2Pes7103Bs7MzP/Rc8aDf0wwVtw==,iv:RMpOCFB/wsFS/qm30n2bdtMp85kfXpreEIJsiHdTlnw=,tag:EoxlLzIFhjv9FNAf0SdiYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdFgyNjdWYldLc0VsNkVU
            Vmo4MlZWdDdIQ0NMSVZYL1N6V3MzOGYxR0FvCnIzbng0azU2ODBwZFEvRmZheWU3
            OFJhTGxVRGJuVWkyaXZPdWd5TzYyRjQKLS0tIHVqTVZBRVA1RXNwMCtKbnFxSGMw
            SVg3WTdudlBLL1hNcmJjNUdqQlRhcFEKoLARQDiInTyPYl3BoFxmkzE1mZm1uJjY
            pJuE7a2ua6TQ8tMk8sIr8FWWZicY6w3LUYSFN7HDBpCL5Xj9pSYIzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:33:42Z"
    mac: ENC[AES256_GCM,data:SQnDUAnaeRL48YB+QimK2PQatvneS1oqizj23PPY2ZRqPW1WplzX9sQ+cYl3XC5YvdN8elbtR23oW29CHXgobDz93Hqs3kHIlj19N2K6FUBs5ZTwNY+J0NiCRURbn93ck+g+tsghguDm+aWij2LPlMqOd9e1kr/K/sf8OLImi58=,iv:2EN2calykoD6n2GSMOOhMqm+ymEpL3tyKFj5wkyjVns=,tag:UQXGfdBMrwX1/6XJJlgK4g==,type:str]
    version: 3.13.3
