apiVersion: v1
kind: Secret
metadata:
    name: sops-secret
    namespace: default
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:IU4h8oQ=,iv:Ibiz5u8yfbjgNfeFteriQ5uZaXbR0l4pjefzJ/8YBVU=,tag:MdHBM/b8WKKHevbx7pLjZw==,type:str]
    password: ENC[AES256_GCM,data:i3RhYAQp+a2JRrKUtXaxUq3ZRoc0,iv:rgMQKdBAhvKfK43aB5zq/fmPgM3eO+Azj81AFy6oCSE=,tag:x7KVRrSVjQw4qWCUIjj9Ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR1VwOWpzSUNzRG03amxG
            MGh1czdIVW5iakp3cW9oK0FUN09JcjNnWGlvCklESVVHUVdNZnVhQUx5aXRPVUwv
            N25HRXMvcGRxV3ZPNzd2ZVIvN1I5TUkKLS0tIE5xU1dZZnBzZDIvaWlxZks2Wkdu
            OUpPczd2VmdsMlo3MzRXTVIxdjVWUDQKQVpNII8yHIAJDbR9FD08Y2fDphO327Xz
            lBK7xu5GKnycwHjUbPlgk9qW6pc11RmAbCVAazW0nhU+kJORHKhs8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T19:49:56Z"
    mac: ENC[AES256_GCM,data:xEfmBxcHLclhOF8tu0yHxRipk3blKiqgjo1uucyRdDIfog09YSxGMPd+cp45YLb6yTbm0Ycr/V7KcmL8EDLgsAJ1vgIa0YcVY52kXobIIZKj5iCVw1CbS+HHad8m5UOzrgS8F+FN+gSDhVVlaYqPKJtM2D/QYjCyqJ1skfRzq1Q=,iv:nZaw/ow7X/0GPrDhgjrehLjqNk35ItBwtvu1boIRX3Q=,tag:CWQAZZSroHcdUvi9dCjdAg==,type:str]
    version: 3.13.2
