apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-nfs
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: audiobookshelf-audiobooks-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.31.213
    path: /mnt/media/Audios/Audiobooks

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts-nfs
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: audiobookshelf-podcasts-nfs
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.31.213
    path: /mnt/media/Audios/Podcasts
