apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-media-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: audiobookshelf-media-nfs

  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2

  nfs:
    server: 192.168.31.213
    path: /mnt/tank/vm-datas/cluster/audiobookshelf
