apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: audiobookshelf-media-nfs
  volumeName: audiobookshelf-media-nfs
  resources:
    requests:
      storage: 2Ti

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce

  volumeMode: Filesystem
  storageClassName: longhorn

  resources:
    requests:
      storage: 30Gi
