apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  suspend: false
  interval: 30m
  timeout: 15m
  releaseName: linkwarden
  targetNamespace: linkwarden
  chart:
    spec:
      chart: linkwarden
      version: 0.5.1
      sourceRef:
        kind: HelmRepository
        name: adnoctem
        namespace: linkwarden
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: linkwarden
    image:
      tag: v2.16.3
      pullPolicy: IfNotPresent
    linkwarden:
      replicas: 1
      domain: link.fanto.dev
      nextAuthSecret:
        existingSecret:
          name: linkwarden-secrets
          key: nextauth-secret
      data:
        storageType: filesystem
        filesystem:
          dataPath: data
          pvc:
            size: 20Gi
            storageClass: longhorn
            reclaimPolicy: Retain
      database:
        existingSecret: linkwarden-secrets
      auth:
        disableRegistration: true
        enableCredentials: true
        sso:
          - provider: oidc
            customName: REPLACE_WITH_OIDC_PROVIDER_NAME
            wellKnownUrl: https://auth.netbird.fantocorp.de/application/o/linkwarden/.well-known/openid-configuration
            scopes: "openid profile email"
            existingSecret: linkwarden-secrets
            clientId: ""
            clientSecret: ""
    extraEnvVars:
      - name: NEXT_PUBLIC_OIDC_ENABLED
        value: "true"
      - name: OIDC_CUSTOM_NAME
        value: Authentik
      - name: OIDC_WELLKNOWN_URL
        value: https://auth.netbird.fantocorp.de/application/o/linkwarden/.well-known/openid-configuration
      - name: OIDC_SCOPES
        value: "openid profile email"
    ingress:
      enabled: false
      tls:
        - hosts:
            - link.fanto.dev
    service:
      type: ClusterIP
      port: 3000
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    startupProbe:
      enabled: true
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 60
    readinessProbe:
      enabled: true
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    livenessProbe:
      enabled: true
      periodSeconds: 30
      timeoutSeconds: 3
      failureThreshold: 3
    postgresql:
      enabled: false
