apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkwarden
resources:
  - ../base
  - helmrelease.yaml
  - helmrepository.yaml
  - httproute.yaml
  - secret.yaml
  - oidc-configmap.yaml
