apiVersion: v1
kind: ConfigMap
metadata:
    name: linkwarden-auth-oidc
data:
    NEXT_PUBLIC_OIDC_ENABLED: ENC[AES256_GCM,data:yasv4w==,iv:iuhJqGScIk8VjPBa0Hb/UwVH2SU5QfaZgJB3TAkOYZo=,tag:hhVtkBvlLnXLU2nXbYk5nQ==,type:str]
    OIDC_CUSTOM_NAME: ENC[AES256_GCM,data:TLsjXwFWbeJef/nfPU0+PFlTHbc=,iv:aXJo1G5oY9xkFP2V6P8paBtApAePFGjXAvIpArs/mfU=,tag:U4yULDTFPX3j8mzv/06FHQ==,type:str]
    OIDC_WELLKNOWN_URL: ENC[AES256_GCM,data:UiZJFuJckGM7wHaJWs+2liin/jcsHCBNhzG/b3IooyCN+Q3l8x6tDALuERwg44Qv9hAfly4sraWrB2PE4eBfQQ6OS6fBX2E7tM8wSmPCwc33XWxWCO6gwXaJIw==,iv:zDy+hqxX+ip1kFHkwpZ25IVvx+JeV5GPvqR0v1s44KI=,tag:/baw2GmO0u+mLU2xS+cOBQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:gfCPBZaJZDaYLt5vymMLciBkohw=,iv:cot7YFBB+zKGqDC0Awaleib4NQCP7eEzXbFTa2n1kpQ=,tag:1OqK3Q1T9LhKMuYTl+X5lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabE1nOVBabi9QZy9WTTcv
            eDBIVXdVUGZvRllFOUgxSVFzbmdjT2t6WXlZCmd0a1gzUzBOc2VlN1JCUTdqSmpq
            dEh1ckdXRVhkbjNibVdwRzBCZEFpbXcKLS0tIEpKeU1hMkxNTGg5bitBcEV1a0dX
            SDNRM3Vmb1Z0VXJwcW5BQi9oeU1mZGsKfqdHV7a9lqEH3VZFgJI2cBxovzw8PYG7
            8q7qteL50GvoSMc+m8Hrv2JCfV+j8FAGgX0JfNToLdbR59uuSjxCZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T08:44:23Z"
    mac: ENC[AES256_GCM,data:aDWrIJ3LVmyY3e/goo9WJACDbHCgHJPtNp1cAlQILg6tZmn5tNoB6YV9ruiSqO9pCNhLXXDj+2lJkowV0ozaM0MG6QGpJUd8bY3qpi4m5O/E70MXu7yNpWYWtbIpksy1L75MulvY+BbprF2fmxJkt86tvMDXm7i01MClbjX7Lu0=,iv:vwmgBwE/Pp56/zHOgDJAayoXmwFXY3wyrLL4OO1pINk=,tag:MFSKwSuhhRc+SCKpoGlCYw==,type:str]
    version: 3.13.3
