apiVersion: v1
kind: ConfigMap
metadata:
    name: linkwarden-auth-oidc
data:
    NEXT_PUBLIC_OIDC_ENABLED: ENC[AES256_GCM,data:h1q3BA==,iv:JGLBur0XFEK6ZJUETaoyZLSRvb+lgBPsVZRNr8+GbyI=,tag:DtY8RosOkxktM/3b1mFowA==,type:str]
    OIDC_CUSTOM_NAME: ENC[AES256_GCM,data:mm+Zkwmphlrf,iv:oqsCpRnAqsP2zFqlcXHs46rl/IcZZUoKcHPDsEsrA9M=,tag:4U46Al6GQWPGelEEToeWjQ==,type:str]
    OIDC_WELLKNOWN_URL: ENC[AES256_GCM,data:gyN9QulZHbHinRgHHqMaF8dfxENHB5KpqXUTF+RHo2WB/D8sLrKYIYdB3+aqkvSecpee9WNZXf1AsvE3xp/1VZIdm+sYtyrvGGapfShngmiX/6LNqMsBfPDQVQ==,iv:DaZopoAiL+RqaBvIHYP1ctIu4F3a87ZLbj3kUZ0w+Qk=,tag:ZgjjocveEL3foqhJ8a0BNQ==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:T4lEZ7/qjN8EEWUrFVjfMnRfar0=,iv:fRFmsij/6a0afaln0Fp9neYIBYmIpKtQy4IckR75i8A=,tag:Jfye1pyt76IsWRU798nECw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcWxhMVNsUnErL2xkMjhv
            UkNGK0FRaW9MYnRrNE4wOXp3WEN1bzRlRDJFClh5dUVtbUc5cDNuRXlCa3lpRTFi
            OWE0MC9nYi83TDV5SnFXTW14bnFBT2MKLS0tIE1ZSlFLcW1saGttYVUwMldPbzQ2
            S0dyUmNjcWlDSEtjWnJ2elEyR01QUXMKpFatks97NBKWd2R1+trOanKHCwjDruGh
            mQj87uBmFsMQbe6Cy6xWDtRJZuv4oJn7rdfzfXZDMIQv7JrrDre0cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T08:12:39Z"
    mac: ENC[AES256_GCM,data:NXKFJIeuO0h5HmxSPDyA8aEH6INMbXhoGUyIdWLgDERt54vDJ5d3nt6qinLCl5/+gHisZsiLBb+AdGs2NKWxebodDK5BCVOoUvA5g3khLNheJjuzZZMsvHfEYndihJZUk6ZMOfDHOmMEEMD47u+SAoRwAzIRJK1y+2RAG1/LbaU=,iv:NsQEwc+6xmcHet+Ue90jqyUfs9n8y1YaGxCSZT4r5Pg=,tag:TzaUebh06KikV2l9PMKyUg==,type:str]
    version: 3.13.3
