apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:78QfdxRQxXgkP588YYwXntWOBUdVM/zUIkLgc0Ma8oXDd0LcpNjyEnOnYi4B+JKE1HjLGArd5BGV9SRXz9uR4EY=,iv:8Z8pig/17u4u5gR/8DE1rZCIuL2lkcbs+CCNxK1T4tQ=,tag:wD4efn9DxzI5Gdfbx+RIYw==,type:str]
    uri: ENC[AES256_GCM,data:gCeS2YtO6talvTlEZVZUZAErvR5MX3CZVeZDjQ5d8OB8f3DeewngjPUPNFEMl+1HjffLzKm+NIEOubX4kHcQ5/VXCTisaVsLKVwt+gnHcYM/5OYYk4jZeb+xC/3qqUQ6wxzCF5Vam0Qk8M1WKeXu1h5Lqf07vj+F6Met5ZgyMd0260ZOTqej,iv:UdXhKNSEE4qBG/TA1UXza3IXESToJ/BeUFStDNSHX2I=,tag:Olm1iaN0ZGhptx5rG00pGA==,type:str]
    clientId: ENC[AES256_GCM,data:xwqP8S7tC9xTEh13CoNzD09Bd9VNUAoJ+E5gy2QKoleIc7oOO+l/2Q==,iv:GrNnKY7YsorkHVHU5TQGnKKGA5qr0hJgvhWbFkiFHXM=,tag:Zo2G45oj6OCoEfkb19Lxow==,type:str]
    clientSecret: ENC[AES256_GCM,data:Zu8yilKgK5zAfVVoYd0YeNdISPPYm5rDcX6R3BFKLI5q/xzjWgTkM/u+YBR0/jP6DBDoNR3ftVLnxct/S0B4r8PlH+73+h4k5Ref3cIqpVzg1N9P3O4Sd+peQpjkJMgTKU0KAD5e9hfAG4ZZ6EBHJsUDFDavm2bRzyTBhWZkVkc=,iv:BzyAMosAcY+orSjSGNjvVo0iOdgypy40FqlggLDh9mI=,tag:0BD580elQ9f930HW6WHjiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R0xCYkkxRjl3c2wwcGlE
            emdGYjNWRGJkSmh2L3ZvNzgxUi9BSS9zcVJBClJuTGFYeHdIcGZCbFlTSGY3Lzk0
            cXJFNEc0dENhUkY0Q3pXTUNhd0hpd3cKLS0tIFZ5K21iUGdhazE1OWxHSW5SeUlq
            bkpmOG9xcmFuUkg1RkdkSGFERktZMTQKz2vD3fQdeSq0pEzxCtf2J5Qf10GsVH/s
            nCrjraanD8vV3OXU77ut0VQfWoe5byEbpc7sTg2hfstVRk5cnwEkPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T07:44:53Z"
    mac: ENC[AES256_GCM,data:jn3Z0cBS7hGWRK6A11JZZSSZZpgwjpanWeXr7loTp60PKY3cu0kO06j5Xjf89P0eDxEQUdNRyJyQ851rEAF4pApHaSTHOQj9sN9DP7SPeD4XFECRXMuTRMofT9XufZqvrUHpx5UIDzs7cclRYxCQm1fqZpzudgOUIJNAzXz/Gjk=,iv:VRBkPu3ySzDPF+v8vjamLT+dTy8Z0ht/eVTaVXQ2G+I=,tag:qwjsks6PZJBemfGHNXrqnQ==,type:str]
    version: 3.13.3
