apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secrets
type: Opaque
stringData:
    nextauth-secret: ENC[AES256_GCM,data:4zIWLQvjkpZy/fObU0vkLJw7hcaA4hBtSgJyfiGQ//Idd18/ItXcbdJXEehG+SyPZhkf7/aCExhZcxnzxJzWIq4=,iv:3n8WB4Ro9bHDBGI6z5z24GqSe1ocVq/4kaW5Sd2Iv7M=,tag:PbPW1Am/UGUEqdQyVsJ8VQ==,type:str]
    uri: ENC[AES256_GCM,data:ECuQNMHf2TV6hX5D8zrAHrWlhJwhf0DSoJ3LcMR272kUK0E+PI+UMZSgBdkF0Oma0+EZigJhoI7stW8nJz9mnlfYuCkoOFHZaZUBOS8W0dVa3qucOLuClraXObmDd3XpOejlIdPQzGiTKcNzlMXncy5kxAAev2DdaPSml+Kt1Xt8YJN+3PG1,iv:t4ncIgB87nwJxq6UUHi/DJT2Fk5/bbebdueaBIkQESk=,tag:5OBBulGzq23iwPs2Oq2o4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT3MzTEI4TlV0c3Y0MDNh
            dis1V0t2Y1ZWdDNhTGZJTU9ZdkNUNGRxc1ZZCkFtSnJjMC8xREluVHQ1dUl2d3pv
            d3dNQnpNbnp6OGNGMzA5NFN6SXdocVEKLS0tIEJEMU1SV1B4eWtwNUhIbG1qR3da
            WXk3YnJ5eFdRbEROMEE1Y1IwRkQ1aFkKbqX8AKYCZKmfkXpIUDv5UzG5zIAor0Lg
            X4njr5kXCjDLbBCv7Qw5cHBHjQw6EoR4dN7h6y2urW5zjISjgpWzHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T06:41:23Z"
    mac: ENC[AES256_GCM,data:4XzW6VwCAdeQUtyyci1LWuhr/AoS8ftue37MxdSmTlo7HnoZBad+hk/vZ0bFW5/DrXRHj9B4Qi6CtHzKClzGo14XjB85FLx+YwudA0fNNL0QibOk7VH4xY8ynf/7Ux1uNf8ewEfhhyKDDq/ENjvUDepFe2ILoNxISO66WR2+bXM=,iv:T81BRc5/e+gH9KdB4ZxXTdqeXv1w41MvvZFB8BHwUfg=,tag:VYWhmjvPHGvqkau8smxVKA==,type:str]
    version: 3.13.3
