# Do not commit a real secret. Encrypt the real secret using this repository's SOPS workflow.
apiVersion: v1
kind: Secret
metadata:
    name: smbsecret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fYqefZ8=,iv:XmUmWLLvoLTd5qOEJnwgUk6/h9AP3t+9CZKxk5uAgUE=,tag:NGt791fPrLc92ATBldhcPA==,type:str]
    password: ENC[AES256_GCM,data:QbYBonTtt03B,iv:78XVxc4JUAFvJXCH1D6bfmjWd9Pij1d0rNbm+/X9vGk=,tag:xUBOvp2nHLsOLXxToMEswg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRzJpendVUXl6TFZwQ0R4
            aFpDUkNqa0E1QVJ2TWFWY1BFdVo4S0N2bWhJCjVXdHpsL0hnRWJnbGs3YVd5SWJp
            R2RDWVEyQ0czenZoMHoxRjcwY1NqYmcKLS0tIFJKV1BjcVl3OWx0T281MXBmaHhN
            bkhLNndEbzVBdmdPNFBTTmFiY1c2R0EKF3Ef8xcewidxGkHMCCa2Sx5rHe6EVET2
            +poygh5gUrgXBd0Zp9TpMC3Ru5ZPc0DkslXTzvRhcg973/ZgOdvbhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T14:37:04Z"
    mac: ENC[AES256_GCM,data:UAn0PcmFk6EWrJoFq5s4Xu7ndgsgy5W2U6qC9jsgW0x2CAe6P5GjZyskSFWSvY3bwujEk0meZ/0oPd9uWwL7ZfC7KAcQhW4py+a8hVwvDQPD8ySU/9vilvE2tNmlDPweGHW0cQ1W8mK5WbneWcoJ88bA5ax2xOcFPpVGOgXpcXI=,iv:7Tv2RgHJlhYIhVuj0PKkLZ0w+vME19xZxus8T93tInc=,tag:S1LpVyt7ctUHFTUywzZgIw==,type:str]
    version: 3.13.3
