apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:rurUpoxrK6lkDKlzhnn8KRQ84E6fvikf1f6qPf84m6uGF18I/uPdK6Wujn8YvPht1vS68Jn/a/+1V1l3zx/C9MvX,iv:ms6nNgwNp88F/94xfq81+1MousMn5Lo9Hht0TfpKAfk=,tag:ySHGvd9ozIdJP1nKxwUBeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK2JOY3pJZC9wWUkzVmlk
            TEYya1JzUHp5UHc1SUVFMUZ2N003dDhXdFQwClpOWFVQcnN3aE1QT1dXSmlKaGZr
            NmFUZm9CdnZJdmNtTTg3K2dSMEQ3dW8KLS0tIHVvNmhMOUFNV1BkNW9VSXFaMWR2
            YU9zQ3kvZnprSzNtNmtxL3lHUVEzVkkKjpR2aBockGiJFWg4XkALXAIAduSSOS+W
            hxEbkiVxFgKpO/Sa6nt1QWaOZUvBn88ledV0sOxpgYFI4bnj514Xrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:22:36Z"
    mac: ENC[AES256_GCM,data:oiGf6+wca1PtoUysdOWRUhBQXxabGaS7vUOZohb+Iu+r3g8qF999Ir7B4RbuoMgzZkFE3ZY4q129T2ddOdyeWIltZ9XfQke0MfMFkCok3lSPkQnZ2D5Io5P2cucFOVMp3nXXWFDRed/UXZ4igV19r9PYFD7wbLPwTS2m47TOzaQ=,iv:NkMGL2OYnb7rcg6wWQvUtOXI3Z+G34IsAgAUdJBAqtA=,tag:xorVanupcsBl6n8HCFeFRQ==,type:str]
    version: 3.13.2
