apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:vr6mZ439U1/XsbtIEUo6zBuEasrzAjlenJ8E2+ykwk90ziDYSHqC4Ea3q0kM453qfNp7yMyUNPMIRPZzCmi5iyy/ukeeJg==,iv:/fN3xLkOc0eu8R3RWPrwquMLVCMWNZJUhF9K3bbGaKA=,tag:KFgEexVssjQz3RauSYf5dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYmxobEhSaG5wd0Q2Zk51
            ZCs1ZU0xeStvV2VsSFpwTlRkbjJsM0Y2U0VBCnZPRVZYZzRBUFBJWXpScEh2ZlBG
            VWkrTXBiRThZWVkrM3pPdThDOUVRRlkKLS0tIFYxT2ZNOEFlR0pLRTEySE1lSDA2
            Y0lVbFNRQkxYcFpiNnVlZTUvNkVTQWcKQX040SDMAuNCXYdGkmNQOseUKW/nm24H
            Uq7KuzXSUM2q4b5q+B54Q/9B2lZYaSpRT+NbqC2IN96Pu7XAo3MOkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age149cx2m4rwfw6argx9fam62vjtcjgeuepd78ej8f0mcpatdgxdqfslqu454
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T19:11:05Z"
    mac: ENC[AES256_GCM,data:KiduaWy+vnfoLhcycDsJdko7NfPsT17NMZbhRAO1Mmzs6xVINMU1los3t/Z6kKYp+ysi3Tm07+GnjrY/7ded5byWq1bxnN9VDrlu/dbrn42Ytlf92GfZcNb+NU2oL/Dcjl5VgmEz3h6nrCRsOGzY5IDCjXFFxXPLXnRiDfYiIiU=,iv:0lAY6ohGFXNFGbzcDEzKzfjvwWXjp+gLb7ipNAMI1ww=,tag:TNE+nvceh7vaBTnsS6NO1w==,type:str]
    version: 3.13.2
