resources:
  - home-assistant
  - proxmenux
  - openspeed
  - adguard
  - uptime-kuma
  - vaultwarden
  - frigate
  - ittools
  - arcane
  - actual-budget
  - affine
  - audiobookshelf
  - netbox
  - patchmon
  - adguardhome-sync
  - zot
  - pbs
  - pgAdmin
  - netalertx
  - n8n
  - hermes
  - paperless
  - opencloud
  - pdf
