resources:
  - home-assistant
  - proxmenux
  - openspeed
  - adguard
  - uptime-kuma
  - vaultwarden
  - frigate
  - ittools
  - arcane
  - actual-budget
  - affine
  - audiobookshelf
  - patchmon
  - zot
  - pbs
  - pgAdmin
  - netalertx
  - n8n
  - hermes
  - paperless
  - opencloud
  - pdf
  - immich
  - jellyfin
  - glance
  - kutt
  - unifi
  - adguardhome-sync
