apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iptv-epg
resources:
  - ../base
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: iptv-epg-channels
    files:
      - channels.xml
